// AUTO-GENERATED by scripts/articles-meta.ts — do not edit by hand.
// Regenerated on every `npm run build`.
/** Glossary term slug → article slugs that mention the term. */
export const termArticleSlugs: Record<string, string[]> = {
  "biocomputer": [
    "vagus-nerve-master-key",
    "dopamine-architecture-mastering-desire",
    "muscle-metabolic-marker",
    "chm-continuous-hormone-monitoring",
    "co2-tolerance-expanding-oxygen-limit",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop"
  ],
  "firmware-update": [
    "cognitive-architecture-nootropic-stacks",
    "muscle-metabolic-marker",
    "femtech-cyclical-architecture"
  ],
  "interoception": [
    "interoceptive-precision-sensor-calibration",
    "neural-signal-to-noise-cleaning-system-channel"
  ],
  "ond-tokens": [
    "dopamine-architecture-mastering-desire"
  ],
  "homeostasis": [
    "dopamine-architecture-mastering-desire",
    "circadian-reset-mastering-light",
    "hrv-training-nervous-system-latency",
    "ai-biomarker-tracking-predictive",
    "fault-tolerant-human-hrv-buffer",
    "fascial-tensegrity-protocol-myofascial-noise"
  ],
  "primary-interoception": [
    "interoceptive-precision-sensor-calibration"
  ],
  "metabolism": [
    "glp1-biology-muscle-preservation",
    "muscle-metabolic-marker",
    "femtech-cyclical-architecture",
    "cacao-stem-cells",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "energy-governor-tsh",
    "adrenal-governor-thermal-runaway",
    "hydraulic-viscosity-onda-transport-bus",
    "zone-2-cardio-mitochondrial-bandwidth"
  ],
  "metabolic-flexibility": [
    "metabolic-flexibility-dual-fuel-system",
    "mitochondrial-biogenesis-cellular-power-grid",
    "glp1-biology-muscle-preservation",
    "mitochondrial-dna-red-light",
    "femtech-cyclical-architecture",
    "energy-sensor-leptin",
    "metabolic-redundancy-hybrid-power-architecture",
    "zone-2-cardio-mitochondrial-bandwidth"
  ],
  "insulin-sensitivity": [
    "metabolic-flexibility-dual-fuel-system",
    "longevity-hardware-cellular-cleanup",
    "glp1-biology-muscle-preservation",
    "muscle-metabolic-marker",
    "glymphatic-flush-clearing-neural-cache",
    "femtech-cyclical-architecture",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "adaptation-hack-range-fractionation",
    "ancestral-sync-circadian-anchors",
    "metabolic-redundancy-hybrid-power-architecture"
  ],
  "glucose-spikes": [
    "metabolic-flexibility-dual-fuel-system",
    "energy-sensor-leptin",
    "protocol-circadian-hard-reset",
    "metabolic-redundancy-hybrid-power-architecture"
  ],
  "mitochondria": [
    "metabolic-flexibility-dual-fuel-system",
    "longevity-hardware-cellular-cleanup",
    "mitochondrial-biogenesis-cellular-power-grid",
    "glp1-biology-muscle-preservation",
    "mitochondrial-dna-red-light",
    "senolytic-high-dosing-longevity",
    "muscle-metabolic-marker",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "neural-optimizer-estrogen",
    "energy-governor-tsh",
    "adaptation-hack-range-fractionation",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "anti-entropy-neural-architecture",
    "metabolic-redundancy-hybrid-power-architecture",
    "zone-2-cardio-mitochondrial-bandwidth"
  ],
  "atp": [
    "circadian-reset-mastering-light",
    "metabolic-flexibility-dual-fuel-system",
    "mitochondrial-biogenesis-cellular-power-grid",
    "mitochondrial-dna-red-light",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "ancestral-sync-circadian-anchors",
    "zone-2-cardio-mitochondrial-bandwidth"
  ],
  "ketosis": [
    "metabolic-flexibility-dual-fuel-system",
    "longevity-hardware-cellular-cleanup",
    "mitochondrial-biogenesis-cellular-power-grid"
  ],
  "autophagy": [
    "metabolic-flexibility-dual-fuel-system",
    "gut-brain-axis-data-link",
    "longevity-hardware-cellular-cleanup",
    "mitochondrial-biogenesis-cellular-power-grid",
    "glp1-biology-muscle-preservation",
    "mitochondrial-dna-red-light",
    "senolytic-high-dosing-longevity",
    "energy-sensor-leptin",
    "adaptation-hack-range-fractionation",
    "longevity-protocol-biological-clock-reset",
    "anti-entropy-neural-architecture"
  ],
  "ketones": [
    "metabolic-flexibility-dual-fuel-system",
    "mitochondrial-biogenesis-cellular-power-grid",
    "metabolic-redundancy-hybrid-power-architecture"
  ],
  "brain": [
    "vagus-nerve-master-key",
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "circadian-reset-mastering-light",
    "metabolic-flexibility-dual-fuel-system",
    "neuroplasticity-flow-overclocking",
    "gut-brain-axis-data-link",
    "breathwork-command-line-interface",
    "hrv-training-nervous-system-latency",
    "digital-dementia-attentional-control",
    "cognitive-architecture-nootropic-stacks",
    "mitochondrial-biogenesis-cellular-power-grid",
    "circadian-lighting-dark-therapy",
    "phase-locked-acoustic-sleep",
    "neural-entrainment-meditation-2",
    "electric-medicine-neuromodulation",
    "muscle-metabolic-marker",
    "glymphatic-flush-clearing-neural-cache",
    "cpg-neural-autopilot",
    "co2-tolerance-expanding-oxygen-limit",
    "femtech-cyclical-architecture",
    "cognitive-architecture-neural-throughput",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "system-stability-serotonin",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "energy-governor-tsh",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "interoceptive-precision-sensor-calibration",
    "neural-signal-to-noise-cleaning-system-channel",
    "biological-latency-optimizing-system-ping",
    "metabolic-redundancy-hybrid-power-architecture",
    "physiological-concentration-flow-state-hardwired",
    "acetylcholine-lens-neuro-mechanics",
    "fascial-tensegrity-protocol-myofascial-noise",
    "bohr-effect-oxygen-telemetry",
    "hydraulic-viscosity-onda-transport-bus"
  ],
  "mind": [
    "glymphatic-flush-clearing-neural-cache",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "interoceptive-precision-sensor-calibration",
    "acc-calibration-protocol-cognitive-control"
  ],
  "vagus-nerve": [
    "vagus-nerve-master-key",
    "gut-brain-axis-data-link",
    "breathwork-command-line-interface",
    "hrv-training-nervous-system-latency",
    "electric-medicine-neuromodulation",
    "chm-continuous-hormone-monitoring",
    "co2-tolerance-expanding-oxygen-limit",
    "system-feedback-biometric-loop",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "system-stability-serotonin",
    "protocol-circadian-hard-reset",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "anti-entropy-neural-architecture",
    "quiet-mode-alpha-cortisol-buffer",
    "rhythmic-entrainment-system-frequencies",
    "adrenal-governor-thermal-runaway",
    "neural-signal-to-noise-cleaning-system-channel",
    "metabolic-redundancy-hybrid-power-architecture",
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "bohr-effect-oxygen-telemetry",
    "hydraulic-viscosity-onda-transport-bus",
    "cold-thermogenesis-adaptation-curve"
  ],
  "mammalian-dive-reflex": [
    "vagus-nerve-master-key",
    "cold-thermogenesis-adaptation-curve"
  ],
  "thalamus": [
    "circadian-reset-mastering-light",
    "energy-sensor-leptin",
    "ancestral-sync-circadian-anchors",
    "baroreflex-01hz-shift",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "rhythmic-entrainment-system-frequencies",
    "neural-signal-to-noise-cleaning-system-channel",
    "cold-thermogenesis-adaptation-curve"
  ],
  "hypothalamus": [
    "circadian-reset-mastering-light",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "ancestral-sync-circadian-anchors",
    "quiet-mode-alpha-cortisol-buffer",
    "cold-thermogenesis-adaptation-curve"
  ],
  "diaphragm": [
    "breathwork-command-line-interface",
    "protocol-circadian-hard-reset",
    "neural-hydraulics-csf-flow",
    "interoceptive-precision-sensor-calibration"
  ],
  "parasympathetic-nervous-system": [
    "vagus-nerve-master-key",
    "hrv-training-nervous-system-latency",
    "electric-medicine-neuromodulation",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "fascial-tensegrity-protocol-myofascial-noise"
  ],
  "sympathetic-nervous-system": [
    "vagus-nerve-master-key",
    "breathwork-command-line-interface",
    "hrv-training-nervous-system-latency",
    "ancestral-sync-circadian-anchors",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "quiet-mode-alpha-cortisol-buffer",
    "adrenal-governor-thermal-runaway",
    "fascial-tensegrity-protocol-myofascial-noise"
  ],
  "insula": [
    "neuroplasticity-flow-overclocking",
    "anti-entropy-neural-architecture",
    "biological-latency-optimizing-system-ping"
  ],
  "cortisol": [
    "vagus-nerve-master-key",
    "circadian-reset-mastering-light",
    "hrv-training-nervous-system-latency",
    "digital-dementia-attentional-control",
    "circadian-lighting-dark-therapy",
    "muscle-metabolic-marker",
    "chm-continuous-hormone-monitoring",
    "femtech-cyclical-architecture",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "energy-governor-tsh",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "cold-thermogenesis-adaptation-curve"
  ],
  "heart-rate-variability": [
    "vagus-nerve-master-key",
    "dopamine-stacking-preventing-circuit-overload",
    "hrv-training-nervous-system-latency",
    "ai-biomarker-tracking-predictive",
    "electric-medicine-neuromodulation",
    "chm-continuous-hormone-monitoring",
    "co2-tolerance-expanding-oxygen-limit",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "adaptation-hack-range-fractionation",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "interoceptive-precision-sensor-calibration",
    "neural-signal-to-noise-cleaning-system-channel",
    "zone-2-cardio-mitochondrial-bandwidth",
    "cold-thermogenesis-adaptation-curve"
  ],
  "central-pattern-generators": [
    "cpg-neural-autopilot",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies"
  ],
  "cerebellum": [
    "spinal-intelligence-decentralized-control"
  ],
  "fascia": [
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "anterior-cingulate-core-coherence-monitoring",
    "hydraulic-viscosity-onda-transport-bus"
  ],
  "neurophysiology": [
    "idle-state-alpha-rhythms"
  ],
  "sensorimotor-cortex": [
    "interoceptive-precision-sensor-calibration"
  ],
  "locomotion": [
    "muscle-metabolic-marker",
    "cpg-neural-autopilot",
    "spinal-harddrive-cpg-autonomous-scripts"
  ],
  "polyvagal-theory": [
    "vagus-nerve-master-key",
    "quiet-mode-alpha-cortisol-buffer"
  ],
  "neuroception": [
    "vagus-nerve-master-key"
  ],
  "neuroplasticity": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "neuroplasticity-flow-overclocking",
    "digital-dementia-attentional-control",
    "cognitive-architecture-nootropic-stacks",
    "neural-entrainment-meditation-2",
    "muscle-metabolic-marker",
    "glymphatic-flush-clearing-neural-cache",
    "cpg-neural-autopilot",
    "femtech-cyclical-architecture",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "neural-optimizer-estrogen",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "spinal-intelligence-decentralized-control"
  ],
  "bdnf": [
    "neuroplasticity-flow-overclocking",
    "muscle-metabolic-marker",
    "neural-optimizer-estrogen"
  ],
  "myelin": [
    "neuroplasticity-flow-overclocking",
    "digital-dementia-attentional-control",
    "quiet-mode-alpha-cortisol-buffer",
    "biological-latency-optimizing-system-ping"
  ],
  "hpa-axis": [
    "hpa-axis-control-cortisol-aggression",
    "quiet-mode-alpha-cortisol-buffer",
    "adrenal-governor-thermal-runaway"
  ],
  "proprioception": [
    "cpg-neural-autopilot",
    "spinal-harddrive-cpg-autonomous-scripts"
  ],
  "lymphatic-system": [
    "circadian-lighting-dark-therapy",
    "phase-locked-acoustic-sleep",
    "glymphatic-flush-clearing-neural-cache",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "protocol-circadian-hard-reset",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow"
  ],
  "motor-cortex": [
    "electric-medicine-neuromodulation"
  ],
  "cognitive-system": [
    "system-stability-serotonin"
  ],
  "pituitary": [
    "hpa-axis-control-cortisol-aggression",
    "energy-governor-tsh"
  ],
  "adrenal": [
    "vagus-nerve-master-key",
    "cacao-stem-cells",
    "hpa-axis-control-cortisol-aggression",
    "quiet-mode-alpha-cortisol-buffer",
    "adrenal-governor-thermal-runaway",
    "bohr-effect-oxygen-telemetry"
  ],
  "adrenaline": [
    "vagus-nerve-master-key",
    "hpa-axis-control-cortisol-aggression",
    "adrenal-governor-thermal-runaway",
    "bohr-effect-oxygen-telemetry"
  ],
  "testosterone": [
    "muscle-metabolic-marker",
    "chm-continuous-hormone-monitoring",
    "endocrine-social-drive-oxytocin-testosterone"
  ],
  "basal-ganglia": [
    "neuroplasticity-flow-overclocking",
    "spinal-intelligence-decentralized-control"
  ],
  "endocrine-system": [
    "endocrine-social-drive-oxytocin-testosterone",
    "adrenal-governor-thermal-runaway",
    "metabolic-redundancy-hybrid-power-architecture"
  ],
  "autonomic-nervous-system": [
    "vagus-nerve-master-key",
    "gut-brain-axis-data-link",
    "breathwork-command-line-interface",
    "hrv-training-nervous-system-latency",
    "ai-biomarker-tracking-predictive",
    "ancestral-sync-circadian-anchors",
    "nervous-system-ping-latency"
  ],
  "coherence": [
    "vagus-nerve-master-key",
    "neuroplasticity-flow-overclocking",
    "hrv-training-nervous-system-latency",
    "neural-entrainment-meditation-2",
    "endocrine-social-drive-oxytocin-testosterone",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "rhythmic-entrainment-system-frequencies",
    "adrenal-governor-thermal-runaway",
    "neural-signal-to-noise-cleaning-system-channel",
    "biological-latency-optimizing-system-ping",
    "fascial-tensegrity-protocol-myofascial-noise",
    "anterior-cingulate-core-coherence-monitoring"
  ],
  "limbic-system": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "digital-dementia-attentional-control"
  ],
  "oxytocin": [
    "endocrine-social-drive-oxytocin-testosterone"
  ],
  "anterior-cingulate-cortex": [
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control"
  ],
  "norepinephrine": [
    "adaptation-hack-range-fractionation",
    "quiet-mode-alpha-cortisol-buffer",
    "physiological-concentration-flow-state-hardwired",
    "cold-thermogenesis-adaptation-curve"
  ],
  "prefrontal-cortex": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "neuroplasticity-flow-overclocking",
    "breathwork-command-line-interface",
    "digital-dementia-attentional-control",
    "cognitive-architecture-nootropic-stacks",
    "mitochondrial-dna-red-light",
    "electric-medicine-neuromodulation",
    "cognitive-architecture-neural-throughput",
    "hpa-axis-control-cortisol-aggression",
    "energy-governor-tsh",
    "nervous-system-ping-latency",
    "baroreflex-01hz-shift",
    "idle-state-alpha-rhythms",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "physiological-concentration-flow-state-hardwired",
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "bohr-effect-oxygen-telemetry"
  ],
  "visual-cortex": [
    "spinal-intelligence-decentralized-control"
  ],
  "biofeedback": [
    "vagus-nerve-master-key",
    "hrv-training-nervous-system-latency",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift"
  ],
  "theta-state": [
    "neuroplasticity-flow-overclocking",
    "digital-dementia-attentional-control",
    "neural-entrainment-meditation-2"
  ],
  "alpha-state": [
    "neuroplasticity-flow-overclocking",
    "digital-dementia-attentional-control",
    "cognitive-architecture-nootropic-stacks",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "neural-signal-to-noise-cleaning-system-channel",
    "biological-latency-optimizing-system-ping"
  ],
  "default-mode-network": [
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway"
  ],
  "dorsal-attention-network": [
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer"
  ],
  "acetylcholine": [
    "vagus-nerve-master-key",
    "cognitive-architecture-nootropic-stacks",
    "physiological-concentration-flow-state-hardwired",
    "acetylcholine-lens-neuro-mechanics",
    "ventral-tegmental-core-motivational-salience",
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "anterior-cingulate-core-coherence-monitoring",
    "hydraulic-viscosity-onda-transport-bus"
  ],
  "locus-coeruleus": [
    "quiet-mode-alpha-cortisol-buffer"
  ],
  "dopamine": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "digital-dementia-attentional-control",
    "cognitive-architecture-nootropic-stacks",
    "system-stability-serotonin",
    "interoceptive-precision-sensor-calibration",
    "physiological-concentration-flow-state-hardwired",
    "ventral-tegmental-core-motivational-salience",
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control",
    "cold-thermogenesis-adaptation-curve"
  ],
  "ventral-tegmental-area": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "ventral-tegmental-core-motivational-salience",
    "vascular-tensegrity-microvascular-mechanics",
    "anterior-cingulate-core-coherence-monitoring"
  ],
  "nucleus-accumbens": [
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "ventral-tegmental-core-motivational-salience"
  ],
  "neurotransmitters": [
    "gut-brain-axis-data-link",
    "neural-signal-to-noise-cleaning-system-channel"
  ],
  "hippocampus": [
    "neuroplasticity-flow-overclocking",
    "neural-optimizer-estrogen",
    "adrenal-governor-thermal-runaway"
  ],
  "predictive-coding": [
    "interoceptive-precision-sensor-calibration",
    "neural-signal-to-noise-cleaning-system-channel",
    "biological-latency-optimizing-system-ping"
  ],
  "reticular-activating-system": [
    "acetylcholine-lens-neuro-mechanics"
  ],
  "flow-state": [
    "vagus-nerve-master-key",
    "neuroplasticity-flow-overclocking",
    "neural-entrainment-meditation-2",
    "cpg-neural-autopilot",
    "neural-hydraulics-csf-flow",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "biological-latency-optimizing-system-ping",
    "physiological-concentration-flow-state-hardwired"
  ],
  "hormones": [
    "neural-optimizer-estrogen",
    "adaptation-hack-range-fractionation"
  ],
  "occipital-cortex": [
    "neural-bridge-alpha-flow-gateway"
  ],
  "synaptic-connections": [
    "neuroplasticity-flow-overclocking"
  ],
  "amygdala": [
    "vagus-nerve-master-key",
    "breathwork-command-line-interface",
    "cognitive-architecture-nootropic-stacks",
    "cognitive-architecture-neural-throughput",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "nightly-flush-glymphatic-neural-cache",
    "idle-state-alpha-rhythms",
    "quiet-mode-alpha-cortisol-buffer",
    "adrenal-governor-thermal-runaway"
  ],
  "thyroid-gland": [
    "energy-governor-tsh"
  ],
  "interference": [
    "dopamine-stacking-preventing-circuit-overload",
    "cognitive-architecture-neural-throughput",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "neural-signal-to-noise-cleaning-system-channel",
    "cold-thermogenesis-adaptation-curve"
  ],
  "feelings": [
    "gut-brain-axis-data-link",
    "interoceptive-precision-sensor-calibration",
    "ventral-tegmental-core-motivational-salience"
  ],
  "thoughts": [
    "vagus-nerve-master-key",
    "gut-brain-axis-data-link",
    "digital-dementia-attentional-control",
    "system-stability-serotonin",
    "neural-signal-to-noise-cleaning-system-channel"
  ],
  "sensations": [
    "interoceptive-precision-sensor-calibration"
  ],
  "synchronization": [
    "neural-entrainment-meditation-2",
    "femtech-cyclical-architecture",
    "cognitive-architecture-neural-throughput",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "nervous-system-ping-latency",
    "baroreflex-01hz-shift",
    "neural-bridge-alpha-flow-gateway",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies"
  ],
  "circadian-rhythm": [
    "dopamine-architecture-mastering-desire",
    "circadian-reset-mastering-light",
    "circadian-lighting-dark-therapy",
    "mitochondrial-dna-red-light",
    "chm-continuous-hormone-monitoring",
    "glymphatic-flush-clearing-neural-cache",
    "femtech-cyclical-architecture",
    "energy-sensor-leptin",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset"
  ],
  "suprachiasmatic-nucleus": [
    "circadian-reset-mastering-light",
    "circadian-lighting-dark-therapy",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors"
  ],
  "melatonin": [
    "circadian-reset-mastering-light",
    "circadian-lighting-dark-therapy",
    "electric-medicine-neuromodulation",
    "cognitive-architecture-neural-throughput",
    "system-stability-serotonin",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nightly-flush-glymphatic-neural-cache"
  ],
  "adenosine": [
    "circadian-reset-mastering-light",
    "cognitive-architecture-nootropic-stacks",
    "idle-state-alpha-rhythms"
  ],
  "blue-light": [
    "circadian-reset-mastering-light",
    "circadian-lighting-dark-therapy",
    "cognitive-architecture-neural-throughput",
    "energy-sensor-leptin",
    "protocol-circadian-hard-reset",
    "longevity-protocol-biological-clock-reset"
  ],
  "deep-sleep": [
    "circadian-reset-mastering-light",
    "neuroplasticity-flow-overclocking",
    "circadian-lighting-dark-therapy",
    "phase-locked-acoustic-sleep",
    "electric-medicine-neuromodulation",
    "glymphatic-flush-clearing-neural-cache",
    "femtech-cyclical-architecture",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "system-stability-serotonin",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "quiet-mode-alpha-cortisol-buffer"
  ],
  "enteric-nervous-system": [
    "gut-brain-axis-data-link",
    "system-stability-serotonin"
  ],
  "serotonin": [
    "gut-brain-axis-data-link",
    "femtech-cyclical-architecture",
    "system-stability-serotonin",
    "neural-optimizer-estrogen"
  ],
  "microbiome": [
    "gut-brain-axis-data-link",
    "system-stability-serotonin"
  ],
  "blood-brain-barrier": [
    "gut-brain-axis-data-link",
    "cognitive-architecture-nootropic-stacks",
    "glymphatic-flush-clearing-neural-cache",
    "co2-tolerance-expanding-oxygen-limit",
    "longevity-protocol-biological-clock-reset"
  ],
  "co2-tolerance": [
    "breathwork-command-line-interface",
    "co2-tolerance-expanding-oxygen-limit",
    "physiological-concentration-flow-state-hardwired",
    "bohr-effect-oxygen-telemetry"
  ],
  "nitric-oxide": [
    "breathwork-command-line-interface",
    "cacao-stem-cells"
  ],
  "tdcs": [
    "electric-medicine-neuromodulation"
  ],
  "ces": [
    "vagus-nerve-master-key",
    "dopamine-architecture-mastering-desire",
    "dopamine-stacking-preventing-circuit-overload",
    "circadian-reset-mastering-light",
    "metabolic-flexibility-dual-fuel-system",
    "neuroplasticity-flow-overclocking",
    "gut-brain-axis-data-link",
    "breathwork-command-line-interface",
    "hrv-training-nervous-system-latency",
    "digital-dementia-attentional-control",
    "longevity-hardware-cellular-cleanup",
    "cognitive-architecture-nootropic-stacks",
    "mitochondrial-biogenesis-cellular-power-grid",
    "circadian-lighting-dark-therapy",
    "mitochondrial-dna-red-light",
    "senolytic-high-dosing-longevity",
    "neural-entrainment-meditation-2",
    "electric-medicine-neuromodulation",
    "muscle-metabolic-marker",
    "chm-continuous-hormone-monitoring",
    "glymphatic-flush-clearing-neural-cache",
    "cpg-neural-autopilot",
    "co2-tolerance-expanding-oxygen-limit",
    "femtech-cyclical-architecture",
    "cacao-stem-cells",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "endocrine-social-drive-oxytocin-testosterone",
    "hpa-axis-control-cortisol-aggression",
    "system-stability-serotonin",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "energy-governor-tsh",
    "adaptation-hack-range-fractionation",
    "protocol-circadian-hard-reset",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "nervous-system-ping-latency",
    "fault-tolerant-human-hrv-buffer",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "idle-state-alpha-rhythms",
    "neural-bridge-alpha-flow-gateway",
    "quiet-mode-alpha-cortisol-buffer",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control",
    "adrenal-governor-thermal-runaway",
    "neural-signal-to-noise-cleaning-system-channel",
    "biological-latency-optimizing-system-ping",
    "metabolic-redundancy-hybrid-power-architecture",
    "physiological-concentration-flow-state-hardwired",
    "acetylcholine-lens-neuro-mechanics",
    "ventral-tegmental-core-motivational-salience",
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "bohr-effect-oxygen-telemetry",
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control",
    "zone-2-cardio-mitochondrial-bandwidth",
    "cold-thermogenesis-adaptation-curve"
  ],
  "f3-zone": [
    "electric-medicine-neuromodulation"
  ],
  "myokines": [
    "muscle-metabolic-marker"
  ],
  "sarcopenia": [
    "glp1-biology-muscle-preservation",
    "muscle-metabolic-marker"
  ],
  "bpc-157-tb-500": [
    "muscle-metabolic-marker"
  ],
  "chm": [
    "chm-continuous-hormone-monitoring",
    "femtech-cyclical-architecture"
  ],
  "lipolysis": [
    "chm-continuous-hormone-monitoring"
  ],
  "free-hormonal-index": [
    "chm-continuous-hormone-monitoring"
  ],
  "glymphatic-pathway": [
    "glymphatic-flush-clearing-neural-cache"
  ],
  "csf": [
    "glymphatic-flush-clearing-neural-cache",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture",
    "quiet-mode-alpha-cortisol-buffer"
  ],
  "deep-maintenance": [
    "glymphatic-flush-clearing-neural-cache"
  ],
  "cpg": [
    "cpg-neural-autopilot",
    "spinal-harddrive-cpg-autonomous-scripts",
    "rhythmic-entrainment-system-frequencies",
    "spinal-intelligence-decentralized-control"
  ],
  "mutual-inhibition": [
    "cpg-neural-autopilot"
  ],
  "ground-contact-time": [
    "cpg-neural-autopilot"
  ],
  "bohr-effect": [
    "co2-tolerance-expanding-oxygen-limit",
    "bohr-effect-oxygen-telemetry"
  ],
  "bolt": [
    "co2-tolerance-expanding-oxygen-limit",
    "bohr-effect-oxygen-telemetry"
  ],
  "hypercapnic-stress": [
    "co2-tolerance-expanding-oxygen-limit"
  ],
  "atp-synthase": [
    "mitochondrial-dna-red-light"
  ],
  "mtdna": [
    "mitochondrial-dna-red-light"
  ],
  "photobiomodulation": [
    "mitochondrial-dna-red-light"
  ],
  "nir": [
    "mitochondrial-dna-red-light"
  ],
  "senescence": [
    "longevity-hardware-cellular-cleanup",
    "senolytic-high-dosing-longevity"
  ],
  "apoptosis": [
    "longevity-hardware-cellular-cleanup",
    "senolytic-high-dosing-longevity"
  ],
  "sasp": [
    "longevity-hardware-cellular-cleanup",
    "senolytic-high-dosing-longevity"
  ],
  "dunedinpace": [
    "longevity-hardware-cellular-cleanup",
    "senolytic-high-dosing-longevity"
  ],
  "predictive-modeling": [
    "interoceptive-precision-sensor-calibration"
  ],
  "biological-signature": [
    "ai-biomarker-tracking-predictive"
  ],
  "micro-drift": [
    "ai-biomarker-tracking-predictive"
  ],
  "telemetry": [
    "ai-biomarker-tracking-predictive",
    "interoceptive-precision-sensor-calibration",
    "ventral-tegmental-core-motivational-salience",
    "bohr-effect-oxygen-telemetry"
  ],
  "phase-locked": [
    "phase-locked-acoustic-sleep",
    "nervous-system-ping-latency",
    "rhythmic-entrainment-system-frequencies"
  ],
  "slow-wave-sleep": [
    "phase-locked-acoustic-sleep"
  ],
  "delta-waves": [
    "phase-locked-acoustic-sleep"
  ],
  "glymphatic-system": [
    "circadian-lighting-dark-therapy",
    "phase-locked-acoustic-sleep",
    "cognitive-architecture-neural-throughput",
    "system-feedback-biometric-loop",
    "protocol-circadian-hard-reset",
    "longevity-protocol-biological-clock-reset",
    "nightly-flush-glymphatic-neural-cache",
    "neural-hydraulics-csf-flow",
    "anti-entropy-neural-architecture"
  ],
  "bone-conduction": [
    "phase-locked-acoustic-sleep"
  ],
  "binaural-beats": [
    "neuroplasticity-flow-overclocking"
  ],
  "frequency-following-response": [
    "neural-entrainment-meditation-2"
  ],
  "brainstem": [
    "vagus-nerve-master-key",
    "gut-brain-axis-data-link",
    "breathwork-command-line-interface",
    "co2-tolerance-expanding-oxygen-limit",
    "hpa-axis-control-cortisol-aggression",
    "resonant-frequency-system-coherence",
    "baroreflex-01hz-shift",
    "idle-state-alpha-rhythms"
  ],
  "co-regulation": [
    "cognitive-architecture-neural-throughput"
  ],
  "tensegrity": [
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "hydraulic-viscosity-onda-transport-bus"
  ],
  "range-fractionation": [
    "adaptation-hack-range-fractionation"
  ],
  "leptin": [
    "circadian-reset-mastering-light",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "adaptation-hack-range-fractionation"
  ],
  "insulin": [
    "metabolic-flexibility-dual-fuel-system",
    "glp1-biology-muscle-preservation",
    "muscle-metabolic-marker",
    "glymphatic-flush-clearing-neural-cache",
    "femtech-cyclical-architecture",
    "cognitive-architecture-neural-throughput",
    "energy-sensor-leptin",
    "neural-optimizer-estrogen",
    "adaptation-hack-range-fractionation",
    "ancestral-sync-circadian-anchors",
    "metabolic-redundancy-hybrid-power-architecture"
  ],
  "glucagon": [
    "glp1-biology-muscle-preservation"
  ],
  "heat-shock-proteins": [
    "longevity-hardware-cellular-cleanup",
    "mitochondrial-biogenesis-cellular-power-grid"
  ],
  "ampk": [
    "longevity-hardware-cellular-cleanup",
    "glp1-biology-muscle-preservation",
    "longevity-protocol-biological-clock-reset"
  ],
  "hormesis": [
    "vagus-nerve-master-key",
    "muscle-metabolic-marker",
    "ancestral-sync-circadian-anchors",
    "longevity-protocol-biological-clock-reset",
    "fault-tolerant-human-hrv-buffer"
  ],
  "motivational-salience": [
    "ventral-tegmental-core-motivational-salience"
  ],
  "prediction-error": [
    "dopamine-architecture-mastering-desire",
    "interoceptive-precision-sensor-calibration",
    "biological-latency-optimizing-system-ping",
    "ventral-tegmental-core-motivational-salience",
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control"
  ],
  "acetylcholine-lens": [
    "acetylcholine-lens-neuro-mechanics",
    "ventral-tegmental-core-motivational-salience",
    "fascial-tensegrity-protocol-myofascial-noise",
    "vascular-tensegrity-microvascular-mechanics",
    "bohr-effect-oxygen-telemetry",
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control",
    "hydraulic-viscosity-onda-transport-bus"
  ],
  "system-jitter": [
    "spinal-harddrive-cpg-autonomous-scripts",
    "fascial-tensegrity-protocol-myofascial-noise",
    "bohr-effect-oxygen-telemetry",
    "anterior-cingulate-core-coherence-monitoring",
    "acc-calibration-protocol-cognitive-control"
  ],
  "hydraulic-viscosity": [
    "vascular-tensegrity-microvascular-mechanics",
    "hydraulic-viscosity-onda-transport-bus"
  ]
}
