/**
 * AUTO-GENERATED by landing/scripts/article-dates.mjs.
 * Do not edit by hand. Regenerated on every `npm run build`.
 *
 * Maps article slug -> { published, modified } ISO timestamps for use in
 * JSON-LD Article schema. The special key __glossary holds the dates that
 * apply to every glossary term (the registry lives in one file).
 */

export const ARTICLE_DATES: Record<string, { published: string; modified: string }> = {
  "acc-calibration-protocol-cognitive-control": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "acetylcholine-lens-neuro-mechanics": {
    "published": "2026-04-22T08:39:02Z",
    "modified": "2026-04-22T17:14:27Z"
  },
  "adaptation-hack-range-fractionation": {
    "published": "2026-03-14T12:57:50Z",
    "modified": "2026-03-14T13:08:20Z"
  },
  "adrenal-governor-thermal-runaway": {
    "published": "2026-04-01T13:38:29Z",
    "modified": "2026-04-01T13:38:29Z"
  },
  "ai-biomarker-tracking-predictive": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "ancestral-sync-circadian-anchors": {
    "published": "2026-03-24T09:54:24Z",
    "modified": "2026-03-24T09:59:17Z"
  },
  "anterior-cingulate-core-coherence-monitoring": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "anti-entropy-neural-architecture": {
    "published": "2026-03-30T20:35:54Z",
    "modified": "2026-03-30T20:35:54Z"
  },
  "baroreflex-01hz-shift": {
    "published": "2026-03-24T13:06:24Z",
    "modified": "2026-03-24T13:12:26Z"
  },
  "biological-latency-optimizing-system-ping": {
    "published": "2026-04-21T12:59:22Z",
    "modified": "2026-04-21T13:29:12Z"
  },
  "bohr-effect-oxygen-telemetry": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "breathwork-command-line-interface": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "cacao-stem-cells": {
    "published": "2026-03-08T12:26:14+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "chm-continuous-hormone-monitoring": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "circadian-lighting-dark-therapy": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "circadian-reset-mastering-light": {
    "published": "2026-02-26T15:36:15+01:00",
    "modified": "2026-03-16T12:12:37Z"
  },
  "co2-tolerance-expanding-oxygen-limit": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "cognitive-architecture-neural-throughput": {
    "published": "2026-03-08T13:29:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "cognitive-architecture-nootropic-stacks": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "cpg-neural-autopilot": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "digital-dementia-attentional-control": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "dopamine-architecture-mastering-desire": {
    "published": "2026-02-26T15:36:15+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "dopamine-stacking-preventing-circuit-overload": {
    "published": "2026-03-08T01:19:56+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "electric-medicine-neuromodulation": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "endocrine-social-drive-oxytocin-testosterone": {
    "published": "2026-03-10T13:31:48Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "energy-governor-tsh": {
    "published": "2026-03-10T22:24:32Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "energy-sensor-leptin": {
    "published": "2026-03-10T14:37:54Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "fascial-tensegrity-protocol-myofascial-noise": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "fault-tolerant-human-hrv-buffer": {
    "published": "2026-03-24T12:53:43Z",
    "modified": "2026-03-24T12:57:43Z"
  },
  "femtech-cyclical-architecture": {
    "published": "2026-03-04T21:35:50+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "glp1-biology-muscle-preservation": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "glymphatic-flush-clearing-neural-cache": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "gut-brain-axis-data-link": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "hpa-axis-control-cortisol-aggression": {
    "published": "2026-03-10T14:37:54Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "hrv-training-nervous-system-latency": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "hydraulic-viscosity-onda-transport-bus": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "idle-state-alpha-rhythms": {
    "published": "2026-03-31T16:27:38Z",
    "modified": "2026-03-31T16:29:58Z"
  },
  "interoceptive-precision-sensor-calibration": {
    "published": "2026-04-21T12:25:38Z",
    "modified": "2026-04-21T12:25:38Z"
  },
  "longevity-hardware-cellular-cleanup": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "longevity-protocol-biological-clock-reset": {
    "published": "2026-03-24T10:01:04Z",
    "modified": "2026-03-24T10:04:43Z"
  },
  "metabolic-flexibility-dual-fuel-system": {
    "published": "2026-02-26T15:36:15+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "metabolic-redundancy-hybrid-power-architecture": {
    "published": "2026-04-21T13:10:41Z",
    "modified": "2026-04-21T13:10:41Z"
  },
  "mitochondrial-biogenesis-cellular-power-grid": {
    "published": "2026-02-26T22:24:55+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "mitochondrial-dna-red-light": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "muscle-metabolic-marker": {
    "published": "2026-03-04T14:27:07+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "nervous-system-ping-latency": {
    "published": "2026-03-24T10:43:38Z",
    "modified": "2026-03-24T10:45:56Z"
  },
  "neural-bridge-alpha-flow-gateway": {
    "published": "2026-03-31T16:32:31Z",
    "modified": "2026-03-31T21:57:09Z"
  },
  "neural-entrainment-meditation-2": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "neural-hydraulics-csf-flow": {
    "published": "2026-03-30T20:30:05Z",
    "modified": "2026-03-30T20:31:04Z"
  },
  "neural-optimizer-estrogen": {
    "published": "2026-03-10T14:37:54Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "neural-signal-to-noise-cleaning-system-channel": {
    "published": "2026-04-21T12:43:38Z",
    "modified": "2026-04-21T13:29:12Z"
  },
  "neuroplasticity-flow-overclocking": {
    "published": "2026-02-26T15:36:15+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "nightly-flush-glymphatic-neural-cache": {
    "published": "2026-03-30T20:04:48Z",
    "modified": "2026-03-30T20:08:31Z"
  },
  "phase-locked-acoustic-sleep": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "physiological-concentration-flow-state-hardwired": {
    "published": "2026-04-22T07:43:40Z",
    "modified": "2026-04-22T17:14:27Z"
  },
  "protocol-circadian-hard-reset": {
    "published": "2026-03-24T09:33:24Z",
    "modified": "2026-03-24T09:43:56Z"
  },
  "quiet-mode-alpha-cortisol-buffer": {
    "published": "2026-03-31T22:01:43Z",
    "modified": "2026-03-31T22:05:25Z"
  },
  "resonant-frequency-system-coherence": {
    "published": "2026-03-24T13:00:58Z",
    "modified": "2026-03-24T13:02:58Z"
  },
  "rhythmic-entrainment-system-frequencies": {
    "published": "2026-03-31T22:29:31Z",
    "modified": "2026-03-31T22:30:36Z"
  },
  "senolytic-high-dosing-longevity": {
    "published": "2026-02-28T20:22:39+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "spinal-harddrive-cpg-autonomous-scripts": {
    "published": "2026-03-31T22:15:23Z",
    "modified": "2026-03-31T22:26:27Z"
  },
  "spinal-intelligence-decentralized-control": {
    "published": "2026-03-31T22:40:04Z",
    "modified": "2026-03-31T22:40:04Z"
  },
  "system-feedback-biometric-loop": {
    "published": "2026-03-09T00:06:14+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "system-stability-serotonin": {
    "published": "2026-03-10T14:37:54Z",
    "modified": "2026-03-12T11:40:20Z"
  },
  "vagus-nerve-master-key": {
    "published": "2026-02-26T14:26:34+01:00",
    "modified": "2026-03-12T11:40:20Z"
  },
  "vascular-tensegrity-microvascular-mechanics": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "ventral-tegmental-core-motivational-salience": {
    "published": "2026-05-01T23:21:51+02:00",
    "modified": "2026-05-01T23:21:51+02:00"
  },
  "__glossary": {
    "published": "2026-02-22T18:17:04+01:00",
    "modified": "2026-05-01T23:21:51+02:00"
  }
}
