/**
 * Version of public/embed/onda-hrv-widget.js (generated by scripts/build-hrv-widget.ts).
 * Bump when the widget's data or wording changes: the embed snippet on /tools/hrv
 * appends ?v=<version> so host pages pick up the new file instead of a cached copy.
 * The bare URL /embed/onda-hrv-widget.js keeps working and serves the same file.
 *   1 — original (unsourced RMSSD bands, percentile tiers)
 *   2 — 2026-10-08 (task 054): Natarajan 2020 Fitbit distribution, sex input, verdicts + disclaimer
 *   3 — 2026-10-08 (task 054 follow-up): sex option "Prefer not to say" → comparison with both groups, no verdict
 */
export const HRV_WIDGET_VERSION = '4'
