/**
 * HRV by age and sex — distribution among Fitbit users (NOT a medical norm).
 *
 * Single source of the numbers: Natarajan A, Pantelopoulos A, Emir-Farinas H,
 * Natarajan P. Heart rate variability with photoplethysmography in 8 million
 * individuals: a cross-sectional study. Lancet Digit Health 2020;2(12):e650–e657
 * (DOI 10.1016/S2589-7500(20)30246-6, PMID 33328029), Supplementary appendix
 * Table S3 ("Typical values for time domain HRV features"), block 6am–7am,
 * columns RMSSD (Female) / RMSSD (Male): median and 25th–75th percentile.
 * Values decoded from the appendix PDF text (glyph codes), checked against the
 * rendered page — see D:\_ONDA\_Sciense\052_by_age_pages.md. Approved by Yakiv
 * 2026-10-08 (task 054).
 *
 * Population: ~8 million Fitbit users, one random day, wrist PPG, still periods,
 * self-reported age/sex. Three of four authors were Fitbit employees; Fitbit
 * funded the study.
 *
 * Rules (owner, 2026-10-08):
 *  - NO interpolation between age points: a user's age maps to the NEAREST age
 *    point and the result says which one ("compared with Fitbit users aged 40–41").
 *  - Verdicts only (no percentile): below p25 → lower than most; above p75 →
 *    higher than most; otherwise within the middle half.
 *  - Every verdict carries HRV_COMPARISON_DISCLAIMER.
 *
 * Also feeds: science/facts.ts (hrv.fitbit.rmssd.am.*), the embed widget
 * (public/embed/onda-hrv-widget.js is GENERATED by scripts/build-hrv-widget.ts)
 * and, after its own step, the ChatGPT/Claude app (scripts/export-chatgpt-data.ts).
 */

import type { ScienceSource } from './sources'

export type HrvSex = 'female' | 'male'

export interface HrvQuartiles {
  p25: number
  p50: number
  p75: number
}

export interface HrvAgePoint {
  /** First and last year of the two-year age point in Table S3. */
  minAge: number
  maxAge: number
  /** Display label, e.g. '40–41'. */
  label: string
  female: HrvQuartiles
  male: HrvQuartiles
}

/** Natarajan 2020, Table S3, 6–7 a.m., RMSSD (ms): median and 25th–75th percentile. */
export const HRV_AGE_POINTS: HrvAgePoint[] = [
  { minAge: 20, maxAge: 21, label: '20–21', female: { p25: 37, p50: 56, p75: 85 }, male: { p25: 45, p50: 66, p75: 96 } },
  { minAge: 25, maxAge: 26, label: '25–26', female: { p25: 32, p50: 48, p75: 73 }, male: { p25: 35, p50: 54, p75: 79 } },
  { minAge: 30, maxAge: 31, label: '30–31', female: { p25: 31, p50: 45, p75: 67 }, male: { p25: 34, p50: 49, p75: 71 } },
  { minAge: 35, maxAge: 36, label: '35–36', female: { p25: 29, p50: 41, p75: 60 }, male: { p25: 31, p50: 43, p75: 62 } },
  { minAge: 40, maxAge: 41, label: '40–41', female: { p25: 26, p50: 37, p75: 52 }, male: { p25: 27, p50: 38, p75: 54 } },
  { minAge: 45, maxAge: 46, label: '45–46', female: { p25: 24, p50: 33, p75: 46 }, male: { p25: 25, p50: 34, p75: 48 } },
  { minAge: 50, maxAge: 51, label: '50–51', female: { p25: 22, p50: 31, p75: 42 }, male: { p25: 23, p50: 31, p75: 42 } },
  { minAge: 55, maxAge: 56, label: '55–56', female: { p25: 22, p50: 29, p75: 40 }, male: { p25: 21, p50: 29, p75: 39 } },
  { minAge: 60, maxAge: 61, label: '60–61', female: { p25: 21, p50: 28, p75: 38 }, male: { p25: 20, p50: 27, p75: 37 } },
]

export const NATARAJAN_2020: ScienceSource = {
  authors: 'Natarajan A, Pantelopoulos A, Emir-Farinas H, Natarajan P',
  year: 2020,
  title: 'Heart rate variability with photoplethysmography in 8 million individuals: a cross-sectional study',
  journal: 'Lancet Digital Health, 2(12):e650–e657 (Supplementary appendix, Table S3)',
  contributes: 'Direct source of the table: RMSSD between 6 and 7 a.m. among about 8 million Fitbit users (wrist optical sensor, still periods), median and 25th–75th percentile by age and sex. Three of the four authors were Fitbit employees and Fitbit funded the study.',
  url: 'https://doi.org/10.1016/S2589-7500(20)30246-6',
}

/** Sources shown on /tools/hrv. Index order matches sourcesContributes in hrv-tool-i18n. */
export const HRV_SOURCES: ScienceSource[] = [
  NATARAJAN_2020,
  {
    authors: 'Task Force of the ESC and NASPE',
    year: 1996,
    title: 'Heart rate variability: standards of measurement, physiological interpretation, and clinical use',
    journal: 'Circulation, 93(5):1043–1065',
    contributes: 'Definition of RMSSD and the measurement standards the literature reports against.',
    url: 'https://doi.org/10.1161/01.CIR.93.5.1043',
  },
]

/** English wording (widget, ChatGPT/Claude app). Page copy is translated in hrv-tool-i18n. */
export const HRV_VERDICT_TEXT: Record<HrvVerdict, string> = {
  lower: 'Lower than most Fitbit users your age',
  middle: 'Within the middle half of Fitbit users your age',
  higher: 'Higher than most Fitbit users your age',
}
export const HRV_COMPARISON_DISCLAIMER =
  'This is a comparison with users of one device, not a medical norm. Your own trend matters more.'

export type HrvVerdict = 'lower' | 'middle' | 'higher'

/** Sex choice in the UI: 'unspecified' ("prefer not to say") shows the comparison with BOTH groups, no single verdict. */
export type HrvSexChoice = HrvSex | 'unspecified'

/** English position wording for the both-groups view (widget, ChatGPT/Claude app). Page copy: hrv-tool-i18n result.position. */
export const HRV_POSITION_TEXT: Record<HrvVerdict, string> = {
  lower: 'below the middle half',
  middle: 'within the middle half',
  higher: 'above the middle half',
}

export interface HrvResult {
  /** Nearest age point in the table (no interpolation). */
  point: HrvAgePoint
  sex: HrvSex
  ref: HrvQuartiles
  verdict: HrvVerdict
  /** True when the age is outside 20–61, so the nearest point is the edge of the data. */
  outsideAgeRange: boolean
}

/** Nearest age point by distance to its two-year span; a tie goes to the younger point. */
export function nearestAgePoint(age: number): HrvAgePoint {
  let best = HRV_AGE_POINTS[0]
  let bestD = Infinity
  for (const p of HRV_AGE_POINTS) {
    const d = age < p.minAge ? p.minAge - age : age > p.maxAge ? age - p.maxAge : 0
    if (d < bestD) {
      best = p
      bestD = d
    }
  }
  return best
}

export function interpretHrv(age: number, rmssd: number, sex: HrvSex): HrvResult {
  const point = nearestAgePoint(age)
  const ref = point[sex]
  const verdict: HrvVerdict = rmssd < ref.p25 ? 'lower' : rmssd > ref.p75 ? 'higher' : 'middle'
  const first = HRV_AGE_POINTS[0]
  const last = HRV_AGE_POINTS[HRV_AGE_POINTS.length - 1]
  return { point, sex, ref, verdict, outsideAgeRange: age < first.minAge || age > last.maxAge }
}

/** Template values for copy that quotes the table ({{f20}}, {{m40}} …: medians at 20–21, 40–41, 60–61). */
export const HRV_COPY_VARS: Record<string, number> = Object.fromEntries(
  HRV_AGE_POINTS.flatMap((p) => [
    [`f${p.minAge}`, p.female.p50],
    [`m${p.minAge}`, p.male.p50],
  ]),
)

/** Comparison with both groups at the nearest age point (sex not given): no single verdict. */
export function interpretHrvBoth(age: number, rmssd: number): Record<HrvSex, HrvResult> {
  return { female: interpretHrv(age, rmssd, 'female'), male: interpretHrv(age, rmssd, 'male') }
}
