// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run build` (or just `node scripts/optimize-images.mjs`) to regenerate.
// Maps every <img src> path to its intrinsic width × height so OptimizedImage
// can render width/height attributes and the browser reserves space at first
// paint (CLS = 0).
export const IMAGE_DIMENSIONS: Record<string, { width: number; height: number }> = {
  "/images/articles/4-7-8-breathing.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/4-7-8-breathing.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/4-7-8-breathing.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/active-intervention-vs-passive-tracking.avif": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/active-intervention-vs-passive-tracking.png": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/active-intervention-vs-passive-tracking.webp": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/adaptation-hack-range-fractionation.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/adaptation-hack-range-fractionation.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/adaptation-hack-range-fractionation.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/adrenal-governor-thermal-runaway.avif": {
    "width": 2752,
    "height": 1536
  },
  "/images/articles/adrenal-governor-thermal-runaway.png": {
    "width": 2752,
    "height": 1536
  },
  "/images/articles/adrenal-governor-thermal-runaway.webp": {
    "width": 2752,
    "height": 1536
  },
  "/images/articles/ai-biomarker-tracking-predictive-longevity-model.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/ai-biomarker-tracking-predictive-longevity-model.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/ai-biomarker-tracking-predictive-longevity-model.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/alternate-nostril-breathing.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/alternate-nostril-breathing.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/alternate-nostril-breathing.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/ancestral-sync-circadian-anchors.avif": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/ancestral-sync-circadian-anchors.png": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/ancestral-sync-circadian-anchors.webp": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/anti-entropy-neural-architecture.avif": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/anti-entropy-neural-architecture.png": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/anti-entropy-neural-architecture.webp": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/anxiety-panic-breathing-hrv.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/anxiety-panic-breathing-hrv.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/anxiety-panic-breathing-hrv.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/app-between-meditation-and-fitness-tracker.avif": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/app-between-meditation-and-fitness-tracker.png": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/app-between-meditation-and-fitness-tracker.webp": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/apple-watch-recovery-hrv-vs-overall-hrv.avif": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/apple-watch-recovery-hrv-vs-overall-hrv.png": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/apple-watch-recovery-hrv-vs-overall-hrv.webp": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/attention-trainable-skill-meditation.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/attention-trainable-skill-meditation.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/attention-trainable-skill-meditation.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/baroreflex-01hz-shift.avif": {
    "width": 1536,
    "height": 652
  },
  "/images/articles/baroreflex-01hz-shift.png": {
    "width": 1536,
    "height": 652
  },
  "/images/articles/baroreflex-01hz-shift.webp": {
    "width": 1536,
    "height": 652
  },
  "/images/articles/bhastrika-pranayama-brain-anxiety.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/bhastrika-pranayama-brain-anxiety.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/bhastrika-pranayama-brain-anxiety.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/biological-latency-optimizing-system-ping.avif": {
    "width": 3168,
    "height": 1344
  },
  "/images/articles/biological-latency-optimizing-system-ping.png": {
    "width": 3168,
    "height": 1344
  },
  "/images/articles/biological-latency-optimizing-system-ping.webp": {
    "width": 3168,
    "height": 1344
  },
  "/images/articles/body-awareness-training-app.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/body-awareness-training-app.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/body-awareness-training-app.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/breathing-altitude-acclimatization.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-altitude-acclimatization.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-altitude-acclimatization.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-exercises-older-adults.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-exercises-older-adults.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-exercises-older-adults.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-for-focus-and-attention.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/breathing-for-focus-and-attention.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/breathing-for-focus-and-attention.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/breathing-lowers-stress-hormones.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-lowers-stress-hormones.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathing-lowers-stress-hormones.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/breathwork-command-line-interface-biohacking.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/breathwork-command-line-interface-biohacking.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/breathwork-command-line-interface-biohacking.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/caffeine-hrv-resting-heart-rate.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/caffeine-hrv-resting-heart-rate.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/caffeine-hrv-resting-heart-rate.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/calm-your-nervous-system-down.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/calm-your-nervous-system-down.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/calm-your-nervous-system-down.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/cardiac-coherence-365-method.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/cardiac-coherence-365-method.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/cardiac-coherence-365-method.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/cardiac-coherence-insomnia-sleep.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/cardiac-coherence-insomnia-sleep.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/cardiac-coherence-insomnia-sleep.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/chronic-stress-nervous-system-never-off.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/chronic-stress-nervous-system-never-off.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/chronic-stress-nervous-system-never-off.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/chronotherapy-light-dark-timing.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/chronotherapy-light-dark-timing.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/chronotherapy-light-dark-timing.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/circadian-lighting-dark-therapy-melatonin-optimization.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/circadian-lighting-dark-therapy-melatonin-optimization.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/circadian-lighting-dark-therapy-melatonin-optimization.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/circadian-rhythm-light-optimization-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/circadian-rhythm-light-optimization-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/circadian-rhythm-light-optimization-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/co2-tolerance-oxygen-efficiency-bohr-effect-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/co2-tolerance-oxygen-efficiency-bohr-effect-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/co2-tolerance-oxygen-efficiency-bohr-effect-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cognitive-architecture-nootropic-stacks-brain-optimization.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cognitive-architecture-nootropic-stacks-brain-optimization.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cognitive-architecture-nootropic-stacks-brain-optimization.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cold-exposure-vagus-nerve.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/cold-exposure-vagus-nerve.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/cold-exposure-vagus-nerve.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/consciousness-training-app.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/consciousness-training-app.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/consciousness-training-app.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/continuous-hormone-monitoring-chm-biohacking-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/continuous-hormone-monitoring-chm-biohacking-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/continuous-hormone-monitoring-chm-biohacking-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cpg-neural-autopilot-spinal-cord-circuits-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cpg-neural-autopilot-spinal-cord-circuits-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/cpg-neural-autopilot-spinal-cord-circuits-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/digital-dementia-attentional-control-neural-optimization.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/digital-dementia-attentional-control-neural-optimization.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/digital-dementia-attentional-control-neural-optimization.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-reward-system-neural-architecture.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-reward-system-neural-architecture.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-reward-system-neural-architecture.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-stacking-circuit-overload.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-stacking-circuit-overload.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dopamine-stacking-circuit-overload.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/dysautonomia-long-covid-breathing.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/dysautonomia-long-covid-breathing.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/dysautonomia-long-covid-breathing.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/eating-late-heart-rate-sleep.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/eating-late-heart-rate-sleep.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/eating-late-heart-rate-sleep.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/electric-medicine-neuromodulation-vagus-nerve-stimulation.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/electric-medicine-neuromodulation-vagus-nerve-stimulation.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/electric-medicine-neuromodulation-vagus-nerve-stimulation.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/endocrine-social-drive-oxytocin-testosterone.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/endocrine-social-drive-oxytocin-testosterone.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/endocrine-social-drive-oxytocin-testosterone.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/energy-sensor-leptin.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/energy-sensor-leptin.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/energy-sensor-leptin.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/fast-vs-slow-pranayama.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/fast-vs-slow-pranayama.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/fast-vs-slow-pranayama.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/fault-tolerant-human-hrv-buffer.avif": {
    "width": 1168,
    "height": 495
  },
  "/images/articles/fault-tolerant-human-hrv-buffer.png": {
    "width": 1168,
    "height": 495
  },
  "/images/articles/fault-tolerant-human-hrv-buffer.webp": {
    "width": 1168,
    "height": 495
  },
  "/images/articles/female-cycle-biohacking-onda.avif": {
    "width": 1024,
    "height": 422
  },
  "/images/articles/female-cycle-biohacking-onda.png": {
    "width": 1024,
    "height": 422
  },
  "/images/articles/female-cycle-biohacking-onda.webp": {
    "width": 1024,
    "height": 422
  },
  "/images/articles/find-your-resonance-breathing-rate.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/find-your-resonance-breathing-rate.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/find-your-resonance-breathing-rate.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/forest-bathing-shinrin-yoku-science.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/forest-bathing-shinrin-yoku-science.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/forest-bathing-shinrin-yoku-science.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/glp-1-biology-muscle-preservation-metabolism.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/glp-1-biology-muscle-preservation-metabolism.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/glp-1-biology-muscle-preservation-metabolism.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/glymphatic-flush-brain-detox-neural-cache-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/glymphatic-flush-brain-detox-neural-cache-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/glymphatic-flush-brain-detox-neural-cache-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/gut-brain-axis-vagus-nerve-data-link.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/gut-brain-axis-vagus-nerve-data-link.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/gut-brain-axis-vagus-nerve-data-link.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/heart-rate-recovery-fitness-marker.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/heart-rate-recovery-fitness-marker.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/heart-rate-recovery-fitness-marker.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/high-blood-pressure-slow-breathing.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/high-blood-pressure-slow-breathing.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/high-blood-pressure-slow-breathing.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/how-much-alcohol-lowers-hrv.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-alcohol-lowers-hrv.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-alcohol-lowers-hrv.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-meditation-do-you-need.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-meditation-do-you-need.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-meditation-do-you-need.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/how-much-water-should-you-drink.avif": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-much-water-should-you-drink.png": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-much-water-should-you-drink.webp": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-beat-jet-lag.avif": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-beat-jet-lag.png": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-beat-jet-lag.webp": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-maintenance-calories.avif": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-maintenance-calories.png": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-maintenance-calories.webp": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-one-rep-max.avif": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-one-rep-max.png": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-calculate-one-rep-max.webp": {
    "width": 2688,
    "height": 1152
  },
  "/images/articles/how-to-measure-hrv-consistently.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-measure-hrv-consistently.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-measure-hrv-consistently.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-raise-hrv-naturally.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-raise-hrv-naturally.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-raise-hrv-naturally.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-regulate-emotions.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-regulate-emotions.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-regulate-emotions.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/how-to-train-your-nervous-system.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/how-to-train-your-nervous-system.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/how-to-train-your-nervous-system.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/hpa-axis-cortisol-aggression.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/hpa-axis-cortisol-aggression.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/hpa-axis-cortisol-aggression.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/hrv-breathing-cold-honest-limits.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-breathing-cold-honest-limits.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-breathing-cold-honest-limits.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-harmony-of-rhythms.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-harmony-of-rhythms.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-harmony-of-rhythms.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/hrv-training-nervous-system-latency-biohacking.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/hrv-training-nervous-system-latency-biohacking.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/hrv-training-nervous-system-latency-biohacking.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/humming-breath-vagus.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/humming-breath-vagus.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/humming-breath-vagus.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/idle-state-alpha-rhythms.avif": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/idle-state-alpha-rhythms.png": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/idle-state-alpha-rhythms.webp": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/interoceptive-precision-sensor-calibration.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/interoceptive-precision-sensor-calibration.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/interoceptive-precision-sensor-calibration.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/jhana-meditation-stages.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/jhana-meditation-stages.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/jhana-meditation-stages.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/longevity-autophagy-cellular-cleanup-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/longevity-autophagy-cellular-cleanup-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/longevity-autophagy-cellular-cleanup-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/longevity-protocol-biological-clock-reset.avif": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/longevity-protocol-biological-clock-reset.png": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/longevity-protocol-biological-clock-reset.webp": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/mbsr-mindfulness-clinical-evidence.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/mbsr-mindfulness-clinical-evidence.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/mbsr-mindfulness-clinical-evidence.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/measuring-meditation-progress.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/measuring-meditation-progress.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/measuring-meditation-progress.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-adverse-effects-safety.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-adverse-effects-safety.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-adverse-effects-safety.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-aging-telomeres.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-aging-telomeres.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-aging-telomeres.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-app-with-biofeedback.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/meditation-app-with-biofeedback.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/meditation-app-with-biofeedback.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/meditation-brain-aging-protection.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-brain-aging-protection.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-brain-aging-protection.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-brain-changes-how-fast.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-brain-changes-how-fast.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-brain-changes-how-fast.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-gamma-waves-experience.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-gamma-waves-experience.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-gamma-waves-experience.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-neuroscience-expert-monks.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-neuroscience-expert-monks.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-neuroscience-expert-monks.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-vs-breathwork.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-vs-breathwork.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-vs-breathwork.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-with-apple-watch.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/meditation-with-apple-watch.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/meditation-with-apple-watch.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/meditation-with-measurable-progress.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-with-measurable-progress.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/meditation-with-measurable-progress.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/metabolic-flexibility-dual-fuel-glucose-ketones-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/metabolic-flexibility-dual-fuel-glucose-ketones-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/metabolic-flexibility-dual-fuel-glucose-ketones-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/metabolic-redundancy-hybrid-power-architecture.avif": {
    "width": 1408,
    "height": 768
  },
  "/images/articles/metabolic-redundancy-hybrid-power-architecture.png": {
    "width": 1408,
    "height": 768
  },
  "/images/articles/metabolic-redundancy-hybrid-power-architecture.webp": {
    "width": 1408,
    "height": 768
  },
  "/images/articles/mitochondrial-biogenesis-cellular-power-grid-optimization.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/mitochondrial-biogenesis-cellular-power-grid-optimization.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/mitochondrial-biogenesis-cellular-power-grid-optimization.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/mitochondrial-dna-red-light-photobiomodulation-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/mitochondrial-dna-red-light-photobiomodulation-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/mitochondrial-dna-red-light-photobiomodulation-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/molecular-psychology-hormonal-firmware.avif": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/molecular-psychology-hormonal-firmware.png": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/molecular-psychology-hormonal-firmware.webp": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/morita-therapy-tracking-paradox.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/morita-therapy-tracking-paradox.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/morita-therapy-tracking-paradox.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/muscle-metabolic-marker-longevity-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/muscle-metabolic-marker-longevity-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/muscle-metabolic-marker-longevity-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/naikan-japanese-reflection.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/naikan-japanese-reflection.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/naikan-japanese-reflection.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/name-it-to-tame-it-affect-labeling.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/name-it-to-tame-it-affect-labeling.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/name-it-to-tame-it-affect-labeling.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/nervous-system-ping-latency.avif": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/nervous-system-ping-latency.png": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/nervous-system-ping-latency.webp": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/neural-bridge-alpha-flow-gateway.avif": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/neural-bridge-alpha-flow-gateway.png": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/neural-bridge-alpha-flow-gateway.webp": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/neural-entrainment-meditation-coherence-onda.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/neural-entrainment-meditation-coherence-onda.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/neural-entrainment-meditation-coherence-onda.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/neural-hydraulics-csf-flow.avif": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/neural-hydraulics-csf-flow.png": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/neural-hydraulics-csf-flow.webp": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/neural-optimizer-estrogen.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neural-optimizer-estrogen.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neural-optimizer-estrogen.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neural-signal-to-noise-system-channel.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neural-signal-to-noise-system-channel.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neural-signal-to-noise-system-channel.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/neuroplasticity-brain-overclocking-flow-state.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/neuroplasticity-brain-overclocking-flow-state.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/neuroplasticity-brain-overclocking-flow-state.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/nicotine-vaping-hrv-heart-rate.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/nicotine-vaping-hrv-heart-rate.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/nicotine-vaping-hrv-heart-rate.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/nightly-flush-glymphatic-neural-cache.avif": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/nightly-flush-glymphatic-neural-cache.png": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/nightly-flush-glymphatic-neural-cache.webp": {
    "width": 1168,
    "height": 784
  },
  "/images/articles/normal-hrv-by-age.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/normal-hrv-by-age.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/normal-hrv-by-age.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/nose-vs-mouth-breathing.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/nose-vs-mouth-breathing.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/nose-vs-mouth-breathing.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/om-chanting-brain-vagus.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/om-chanting-brain-vagus.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/om-chanting-brain-vagus.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/onda-cacao-stem-cell-regeneration-matrix.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-cacao-stem-cell-regeneration-matrix.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-cacao-stem-cell-regeneration-matrix.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-neural-architecture-optimization.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-neural-architecture-optimization.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-neural-architecture-optimization.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-system-feedback-biometric-loop.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-system-feedback-biometric-loop.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/onda-system-feedback-biometric-loop.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/overtraining-hrv-resting-heart-rate.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/overtraining-hrv-resting-heart-rate.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/overtraining-hrv-resting-heart-rate.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/phase-locked-acoustic-sleep-delta-wave-stimulation.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/phase-locked-acoustic-sleep-delta-wave-stimulation.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/phase-locked-acoustic-sleep-delta-wave-stimulation.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/physiological-concentration-flow-state-hardwired.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/physiological-concentration-flow-state-hardwired.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/physiological-concentration-flow-state-hardwired.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/physiological-sigh.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/physiological-sigh.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/physiological-sigh.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/pranayama-metabolic-syndrome.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/pranayama-metabolic-syndrome.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/pranayama-metabolic-syndrome.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/protocol-circadian-hard-reset.avif": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/protocol-circadian-hard-reset.png": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/protocol-circadian-hard-reset.webp": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/quiet-mode-alpha-cortisol-buffer.avif": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/quiet-mode-alpha-cortisol-buffer.png": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/quiet-mode-alpha-cortisol-buffer.webp": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/rajyoga-open-eye-meditation.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/rajyoga-open-eye-meditation.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/rajyoga-open-eye-meditation.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/resonant-frequency-system-coherence.avif": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/resonant-frequency-system-coherence.png": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/resonant-frequency-system-coherence.webp": {
    "width": 1168,
    "height": 496
  },
  "/images/articles/respiratory-rate-hidden-signal.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/respiratory-rate-hidden-signal.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/respiratory-rate-hidden-signal.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/resting-heart-rate-by-age.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/resting-heart-rate-by-age.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/resting-heart-rate-by-age.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/rhythmic-entrainment-system-frequencies.avif": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/rhythmic-entrainment-system-frequencies.png": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/rhythmic-entrainment-system-frequencies.webp": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/screen-apnea-breathing.avif": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/screen-apnea-breathing.png": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/screen-apnea-breathing.webp": {
    "width": 1672,
    "height": 940
  },
  "/images/articles/senolytic-high-dosing-longevity-zombie-cells-purge.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/senolytic-high-dosing-longevity-zombie-cells-purge.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/senolytic-high-dosing-longevity-zombie-cells-purge.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/short-daily-breathing-routine.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/short-daily-breathing-routine.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/short-daily-breathing-routine.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/sitting-all-day-nervous-system.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/sitting-all-day-nervous-system.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/sitting-all-day-nervous-system.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/social-jet-lag-irregular-sleep.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/social-jet-lag-irregular-sleep.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/social-jet-lag-irregular-sleep.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/spinal-harddrive-cpg-autonomous-scripts.avif": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/spinal-harddrive-cpg-autonomous-scripts.png": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/spinal-harddrive-cpg-autonomous-scripts.webp": {
    "width": 1536,
    "height": 1024
  },
  "/images/articles/spinal-intelligence-decentralized-control.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/spinal-intelligence-decentralized-control.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/spinal-intelligence-decentralized-control.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/structured-meditation-training-by-levels.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/structured-meditation-training-by-levels.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/structured-meditation-training-by-levels.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/sudarshan-kriya-yoga-breathing.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/sudarshan-kriya-yoga-breathing.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/sudarshan-kriya-yoga-breathing.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/system-stability-serotonin.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/system-stability-serotonin.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/system-stability-serotonin.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/tanden-breathing-serotonin.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/tanden-breathing-serotonin.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/tanden-breathing-serotonin.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/the-acetylcholine-shader.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/the-acetylcholine-shader.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/the-acetylcholine-shader.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/train-hrv-iphone-camera-no-wearable.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/train-hrv-iphone-camera-no-wearable.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/train-hrv-iphone-camera-no-wearable.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/trataka-candle-gazing-focus.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/trataka-candle-gazing-focus.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/trataka-candle-gazing-focus.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/tsh-energy-governor.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/tsh-energy-governor.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/tsh-energy-governor.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/vagus-nerve-biohacking-data-highway.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/vagus-nerve-biohacking-data-highway.png": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/vagus-nerve-biohacking-data-highway.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/articles/vipassana-meditation-attention-brain.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/vipassana-meditation-attention-brain.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/vipassana-meditation-attention-brain.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/wearables-train-not-just-track.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/wearables-train-not-just-track.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/wearables-train-not-just-track.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/what-is-my-chronotype.avif": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/what-is-my-chronotype.png": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/what-is-my-chronotype.webp": {
    "width": 1584,
    "height": 672
  },
  "/images/articles/what-to-do-after-low-hrv-reading.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/what-to-do-after-low-hrv-reading.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/what-to-do-after-low-hrv-reading.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/what-your-apple-watch-records.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/what-your-apple-watch-records.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/what-your-apple-watch-records.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/wim-hof-breathing-inflammation.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/wim-hof-breathing-inflammation.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/wim-hof-breathing-inflammation.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/wind-down-before-sleep-breathing.avif": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/wind-down-before-sleep-breathing.png": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/wind-down-before-sleep-breathing.webp": {
    "width": 2560,
    "height": 1440
  },
  "/images/articles/yoga-breathing-diabetes-blood-sugar.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-breathing-diabetes-blood-sugar.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-breathing-diabetes-blood-sugar.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-nidra-sleep-science.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-nidra-sleep-science.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-nidra-sleep-science.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-poses-heart-rate-blood-pressure.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-poses-heart-rate-blood-pressure.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/yoga-poses-heart-rate-blood-pressure.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/your-baseline-knows-first.avif": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/your-baseline-knows-first.png": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/your-baseline-knows-first.webp": {
    "width": 1672,
    "height": 941
  },
  "/images/articles/zazen-zen-meditation-brain.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/zazen-zen-meditation-brain.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/zazen-zen-meditation-brain.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/zen-koans-brain-cognition.avif": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/zen-koans-brain-cognition.jpg": {
    "width": 1920,
    "height": 820
  },
  "/images/articles/zen-koans-brain-cognition.webp": {
    "width": 1920,
    "height": 820
  },
  "/images/body-fat-percentage-composition.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/body-fat-percentage-composition.png": {
    "width": 1915,
    "height": 821
  },
  "/images/body-fat-percentage-composition.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/box-breathing-how-it-works.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/box-breathing-how-it-works.png": {
    "width": 1915,
    "height": 821
  },
  "/images/box-breathing-how-it-works.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/caffeine-half-life-sleep-pressure.avif": {
    "width": 1914,
    "height": 822
  },
  "/images/caffeine-half-life-sleep-pressure.png": {
    "width": 1914,
    "height": 822
  },
  "/images/caffeine-half-life-sleep-pressure.webp": {
    "width": 1914,
    "height": 822
  },
  "/images/cognitive-shuffling.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/cognitive-shuffling.png": {
    "width": 1915,
    "height": 821
  },
  "/images/cognitive-shuffling.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/coherent-breathing-guide.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/coherent-breathing-guide.png": {
    "width": 1915,
    "height": 821
  },
  "/images/coherent-breathing-guide.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/does-dopamine-detox-work.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/does-dopamine-detox-work.png": {
    "width": 1915,
    "height": 821
  },
  "/images/does-dopamine-detox-work.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/home/hero-phone-v3.avif": {
    "width": 760,
    "height": 1577
  },
  "/images/home/hero-phone-v3.png": {
    "width": 760,
    "height": 1577
  },
  "/images/home/hero-phone-v3.webp": {
    "width": 760,
    "height": 1577
  },
  "/images/home/proof-v2.avif": {
    "width": 600,
    "height": 1254
  },
  "/images/home/proof-v2.png": {
    "width": 600,
    "height": 1254
  },
  "/images/home/proof-v2.webp": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-1-v2.avif": {
    "width": 600,
    "height": 1250
  },
  "/images/home/showcase-1-v2.png": {
    "width": 600,
    "height": 1250
  },
  "/images/home/showcase-1-v2.webp": {
    "width": 600,
    "height": 1250
  },
  "/images/home/showcase-2-v2.avif": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-2-v2.png": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-2-v2.webp": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-3-v2.avif": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-3-v2.png": {
    "width": 600,
    "height": 1254
  },
  "/images/home/showcase-3-v2.webp": {
    "width": 600,
    "height": 1254
  },
  "/images/how-long-does-alcohol-stay-in-your-system.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/how-long-does-alcohol-stay-in-your-system.png": {
    "width": 1915,
    "height": 821
  },
  "/images/how-long-does-alcohol-stay-in-your-system.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/how-much-sleep-do-you-need.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/how-much-sleep-do-you-need.png": {
    "width": 1915,
    "height": 821
  },
  "/images/how-much-sleep-do-you-need.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-get-rid-of-brain-fog.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-get-rid-of-brain-fog.png": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-get-rid-of-brain-fog.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-lower-cortisol.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-lower-cortisol.png": {
    "width": 1915,
    "height": 821
  },
  "/images/how-to-lower-cortisol.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/hrv-different-every-device.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/hrv-different-every-device.png": {
    "width": 1915,
    "height": 821
  },
  "/images/hrv-different-every-device.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/intermittent-fasting-metabolic-switch.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/intermittent-fasting-metabolic-switch.png": {
    "width": 1915,
    "height": 821
  },
  "/images/intermittent-fasting-metabolic-switch.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/parts/onda-part-1-i-am-conscious-architecture.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-1-i-am-conscious-architecture.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-1-i-am-conscious-architecture.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-2-i-move-kinetic-architecture.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-2-i-move-kinetic-architecture.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-2-i-move-kinetic-architecture.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-3-i-adapt-biological-resilience.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-3-i-adapt-biological-resilience.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-3-i-adapt-biological-resilience.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-4-i-maneuver-cognitive-strategy-matrix.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-4-i-maneuver-cognitive-strategy-matrix.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-4-i-maneuver-cognitive-strategy-matrix.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-5-i-guard-territory-immune-security.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-5-i-guard-territory-immune-security.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-5-i-guard-territory-immune-security.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-6-pack-synchronization-social-intelligence.avif": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-6-pack-synchronization-social-intelligence.png": {
    "width": 1024,
    "height": 434
  },
  "/images/parts/onda-part-6-pack-synchronization-social-intelligence.webp": {
    "width": 1024,
    "height": 434
  },
  "/images/protein-intake-muscle-protein-synthesis.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/protein-intake-muscle-protein-synthesis.png": {
    "width": 1915,
    "height": 821
  },
  "/images/protein-intake-muscle-protein-synthesis.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/topics/brain-focus-aging.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/brain-focus-aging.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/brain-focus-aging.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/breathing.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/breathing.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/breathing.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/heart-fitness-metabolism.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/heart-fitness-metabolism.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/heart-fitness-metabolism.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/hrv-heart-rate.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/hrv-heart-rate.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/hrv-heart-rate.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/lifestyle.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/lifestyle.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/lifestyle.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/meditation.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/meditation.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/meditation.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/sleep-body-clock.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/sleep-body-clock.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/sleep-body-clock.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/stress-vagus.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/stress-vagus.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/stress-vagus.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/world.avif": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/world.jpg": {
    "width": 1600,
    "height": 1200
  },
  "/images/topics/world.webp": {
    "width": 1600,
    "height": 1200
  },
  "/images/vagus-nerve-exercises.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/vagus-nerve-exercises.png": {
    "width": 1915,
    "height": 821
  },
  "/images/vagus-nerve-exercises.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/vo2max-increase-aerobic-engine.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/vo2max-increase-aerobic-engine.png": {
    "width": 1915,
    "height": 821
  },
  "/images/vo2max-increase-aerobic-engine.webp": {
    "width": 1915,
    "height": 821
  },
  "/images/zone-2-training-aerobic-base.avif": {
    "width": 1915,
    "height": 821
  },
  "/images/zone-2-training-aerobic-base.png": {
    "width": 1915,
    "height": 821
  },
  "/images/zone-2-training-aerobic-base.webp": {
    "width": 1915,
    "height": 821
  },
  "/og-emoton.avif": {
    "width": 1200,
    "height": 630
  },
  "/og-emoton.png": {
    "width": 1200,
    "height": 630
  },
  "/og-emoton.webp": {
    "width": 1200,
    "height": 630
  },
  "/og-preview.avif": {
    "width": 1200,
    "height": 630
  },
  "/og-preview.png": {
    "width": 1200,
    "height": 630
  },
  "/og-preview.webp": {
    "width": 1200,
    "height": 630
  },
  "/onda-life-hrv-consciousness-hero.avif": {
    "width": 1024,
    "height": 682
  },
  "/onda-life-hrv-consciousness-hero.png": {
    "width": 1024,
    "height": 682
  },
  "/onda-life-hrv-consciousness-hero.webp": {
    "width": 1024,
    "height": 682
  },
  "/tools/baseline/card-bg.avif": {
    "width": 1080,
    "height": 1920
  },
  "/tools/baseline/card-bg.jpg": {
    "width": 1080,
    "height": 1920
  },
  "/tools/baseline/card-bg.webp": {
    "width": 1080,
    "height": 1920
  }
} as const
