// AUTO-GENERATED by scripts/generate-localized-coverage.ts — do not edit.
// Per-locale slugs that have a prerendered localized page; used by langHref()
// to fall back to the EN URL for untranslated content (avoids /<lang>/... soft-404s).
export const LOCALIZED_COVERAGE: Record<string, { articles: Set<string>; glossary: Set<string>; reviews: Set<string> }> = {
  es: {
    articles: new Set(['baroreflex-01hz-shift', 'breathwork-command-line-interface', 'chm-continuous-hormone-monitoring', 'circadian-reset-mastering-light', 'co2-tolerance-expanding-oxygen-limit', 'cpg-neural-autopilot', 'dopamine-architecture-mastering-desire', 'dopamine-stacking-preventing-circuit-overload', 'electric-medicine-neuromodulation', 'fault-tolerant-human-hrv-buffer', 'glymphatic-flush-clearing-neural-cache', 'gut-brain-axis-data-link', 'idle-state-alpha-rhythms', 'interoceptive-precision-sensor-calibration', 'metabolic-flexibility-dual-fuel-system', 'muscle-metabolic-marker', 'nervous-system-ping-latency', 'neural-entrainment-meditation-2', 'neuroplasticity-flow-overclocking', 'nightly-flush-glymphatic-neural-cache', 'resonant-frequency-system-coherence', 'vagus-nerve-master-key']),
    glossary: new Set([]),
    reviews: new Set(['', 'apple-watch-series-11', 'autosleep', 'balance', 'bettersleep', 'buddhify', 'calm', 'compare/best-hrv-trackers-2026', 'compare/best-meditation-apps-2026', 'compare/best-sleep-apps-2026', 'endel', 'fitbit-charge-6', 'garmin-venu-4', 'happier-meditation', 'headspace', 'healthy-minds-program', 'insight-timer', 'medito', 'methodology', 'oura-ring-4', 'pillow', 'polar-h10', 'pzizz', 'ringconn-gen-2', 'rise', 'samsung-galaxy-ring', 'sleep-as-android', 'sleep-cycle', 'sleepio', 'sleepscore', 'smiling-mind', 'ultrahuman-ring-air', 'waking-up', 'whoop-5-0', 'withings-scanwatch']),
  },
  ru: {
    articles: new Set(['chm-continuous-hormone-monitoring', 'circadian-reset-mastering-light', 'co2-tolerance-expanding-oxygen-limit', 'cpg-neural-autopilot', 'dopamine-architecture-mastering-desire', 'electric-medicine-neuromodulation', 'glymphatic-flush-clearing-neural-cache', 'gut-brain-axis-data-link', 'molecular-psychology-hormonal-firmware', 'muscle-metabolic-marker', 'neural-entrainment-meditation-2', 'neuroplasticity-flow-overclocking', 'vagus-nerve-master-key']),
    glossary: new Set([]),
    reviews: new Set(['', 'apple-watch-series-11', 'autosleep', 'balance', 'bettersleep', 'buddhify', 'calm', 'compare/best-hrv-trackers-2026', 'compare/best-meditation-apps-2026', 'compare/best-sleep-apps-2026', 'endel', 'fitbit-charge-6', 'garmin-venu-4', 'happier-meditation', 'headspace', 'healthy-minds-program', 'insight-timer', 'medito', 'methodology', 'oura-ring-4', 'pillow', 'polar-h10', 'pzizz', 'ringconn-gen-2', 'rise', 'samsung-galaxy-ring', 'sleep-as-android', 'sleep-cycle', 'sleepio', 'sleepscore', 'smiling-mind', 'ultrahuman-ring-air', 'waking-up', 'whoop-5-0', 'withings-scanwatch']),
  },
  uk: {
    articles: new Set([]),
    glossary: new Set([]),
    reviews: new Set(['', 'apple-watch-series-11', 'autosleep', 'bettersleep', 'compare/best-hrv-trackers-2026', 'compare/best-sleep-apps-2026', 'endel', 'fitbit-charge-6', 'garmin-venu-4', 'methodology', 'oura-ring-4', 'pillow', 'polar-h10', 'pzizz', 'ringconn-gen-2', 'rise', 'samsung-galaxy-ring', 'sleep-as-android', 'sleep-cycle', 'sleepio', 'sleepscore', 'ultrahuman-ring-air', 'whoop-5-0', 'withings-scanwatch']),
  },
  zh: {
    articles: new Set([]),
    glossary: new Set([]),
    reviews: new Set([]),
  },
}
