/**
 * Release queue for translated pages (owner decision 2026-10-07): ONE site-wide stream —
 * {PER_BATCH} pages in total every {EVERY_DAYS} days, from QUEUE_START. Languages take turns
 * (round-robin, one page per language per turn); each language's turn list is its queued
 * articles followed by the queued review pages (same review list for every language).
 *
 * To queue a newly translated article: append its slug to that language's list (append only —
 * positions set the dates). Only add slugs whose translation body already exists in
 * public/locales/<lang>/articles.json. NB: the gate is the BUILD date; the scheduled
 * rebuild (.github/workflows/landing-scheduled-rebuild.yml) runs daily.
 */
import type { PublishEntry, PublishCollection } from './locale-publish'

export const QUEUE_START = '2026-10-08'
export const PER_BATCH = 20
export const EVERY_DAYS = 2
const LANG_ORDER = ['es', 'ru', 'uk', 'zh', 'de', 'fr', 'it', 'pt', 'nl', 'pl', 'ja']

export const ARTICLE_RELEASE_QUEUE: Record<string, readonly string[]> = {
  es: [
    'name-it-to-tame-it-affect-labeling',
    'cold-exposure-vagus-nerve',
    'nicotine-vaping-hrv-heart-rate',
    'short-daily-breathing-routine',
    'find-your-resonance-breathing-rate',
    'train-hrv-iphone-camera-no-wearable',
    'calm-your-nervous-system-down',
    'body-awareness-training-app',
    'consciousness-training-app',
    'breathing-for-focus-and-attention',
    'wearables-train-not-just-track',
    'wind-down-before-sleep-breathing',
    'how-to-regulate-emotions',
    'meditation-with-apple-watch',
    'anxiety-panic-breathing-hrv',
    'dysautonomia-long-covid-breathing',
    'high-blood-pressure-slow-breathing',
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  ru: [
    'glp1-biology-muscle-preservation',
    'metabolic-flexibility-dual-fuel-system',
    'mitochondrial-biogenesis-cellular-power-grid',
    'mitochondrial-dna-red-light',
    'longevity-hardware-cellular-cleanup',
    'senolytic-high-dosing-longevity',
    'energy-governor-tsh',
    'energy-sensor-leptin',
    'neural-optimizer-estrogen',
    'femtech-cyclical-architecture',
    'endocrine-social-drive-oxytocin-testosterone',
    'acc-calibration-protocol-cognitive-control',
    'acetylcholine-lens-neuro-mechanics',
    'adaptation-hack-range-fractionation',
    'ai-biomarker-tracking-predictive',
    'anterior-cingulate-core-coherence-monitoring',
    'cacao-stem-cells',
    'cognitive-architecture-neural-throughput',
    'cognitive-architecture-nootropic-stacks',
    'digital-dementia-attentional-control',
    'hydraulic-viscosity-onda-transport-bus',
    'neural-hydraulics-csf-flow',
    'neural-signal-to-noise-cleaning-system-channel',
    'spinal-harddrive-cpg-autonomous-scripts',
    'spinal-intelligence-decentralized-control',
    'system-feedback-biometric-loop',
    'system-stability-serotonin',
    'vascular-tensegrity-microvascular-mechanics',
    'ventral-tegmental-core-motivational-salience',
    'fascial-tensegrity-protocol-myofascial-noise',
    'respiratory-rate-hidden-signal',
    'heart-rate-recovery-fitness-marker',
    'screen-apnea-breathing',
    'caffeine-hrv-resting-heart-rate',
    'social-jet-lag-irregular-sleep',
    'eating-late-heart-rate-sleep',
    'chronic-stress-nervous-system-never-off',
    'sitting-all-day-nervous-system',
    'name-it-to-tame-it-affect-labeling',
    'cold-exposure-vagus-nerve',
    'nicotine-vaping-hrv-heart-rate',
    'how-to-train-your-nervous-system',
    'meditation-app-with-biofeedback',
    'structured-meditation-training-by-levels',
    'app-between-meditation-and-fitness-tracker',
    'short-daily-breathing-routine',
    'find-your-resonance-breathing-rate',
    'train-hrv-iphone-camera-no-wearable',
    'calm-your-nervous-system-down',
    'body-awareness-training-app',
    'consciousness-training-app',
    'breathing-for-focus-and-attention',
    'wearables-train-not-just-track',
    'wind-down-before-sleep-breathing',
    'how-to-regulate-emotions',
    'meditation-with-apple-watch',
    'anxiety-panic-breathing-hrv',
    'dysautonomia-long-covid-breathing',
    'high-blood-pressure-slow-breathing',
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  zh: [
    'acc-calibration-protocol-cognitive-control',
    'acetylcholine-lens-neuro-mechanics',
    'adaptation-hack-range-fractionation',
    'adrenal-governor-thermal-runaway',
    'ai-biomarker-tracking-predictive',
    'ancestral-sync-circadian-anchors',
    'anterior-cingulate-core-coherence-monitoring',
    'anti-entropy-neural-architecture',
    'baroreflex-01hz-shift',
    'breathwork-command-line-interface',
    'cacao-stem-cells',
    'circadian-lighting-dark-therapy',
    'circadian-reset-mastering-light',
    'cognitive-architecture-neural-throughput',
    'cognitive-architecture-nootropic-stacks',
    'cpg-neural-autopilot',
    'digital-dementia-attentional-control',
    'electric-medicine-neuromodulation',
    'energy-governor-tsh',
    'fascial-tensegrity-protocol-myofascial-noise',
    'fault-tolerant-human-hrv-buffer',
    'femtech-cyclical-architecture',
    'glp1-biology-muscle-preservation',
    'gut-brain-axis-data-link',
    'hpa-axis-control-cortisol-aggression',
    'hydraulic-viscosity-onda-transport-bus',
    'interoceptive-precision-sensor-calibration',
    'longevity-hardware-cellular-cleanup',
    'longevity-protocol-biological-clock-reset',
    'mitochondrial-biogenesis-cellular-power-grid',
    'mitochondrial-dna-red-light',
    'muscle-metabolic-marker',
    'neural-entrainment-meditation-2',
    'neural-hydraulics-csf-flow',
    'neural-signal-to-noise-cleaning-system-channel',
    'neuroplasticity-flow-overclocking',
    'phase-locked-acoustic-sleep',
    'physiological-concentration-flow-state-hardwired',
    'protocol-circadian-hard-reset',
    'resonant-frequency-system-coherence',
    'rhythmic-entrainment-system-frequencies',
    'senolytic-high-dosing-longevity',
    'spinal-harddrive-cpg-autonomous-scripts',
    'spinal-intelligence-decentralized-control',
    'system-feedback-biometric-loop',
    'vascular-tensegrity-microvascular-mechanics',
    'ventral-tegmental-core-motivational-salience',
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  uk: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  de: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  fr: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  it: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  pt: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  nl: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  pl: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
  ja: [
    'attention-trainable-skill-meditation',
    'breathing-altitude-acclimatization',
    'breathing-exercises-older-adults',
    'breathing-lowers-stress-hormones',
    'chronotherapy-light-dark-timing',
    'fast-vs-slow-pranayama',
    'forest-bathing-shinrin-yoku-science',
    'hrv-breathing-cold-honest-limits',
    'hrv-harmony-of-rhythms',
    'jhana-meditation-stages',
    'mbsr-mindfulness-clinical-evidence',
    'meditation-adverse-effects-safety',
    'meditation-aging-telomeres',
    'meditation-brain-aging-protection',
    'meditation-brain-changes-how-fast',
    'meditation-gamma-waves-experience',
    'meditation-neuroscience-expert-monks',
    'meditation-with-measurable-progress',
    'naikan-japanese-reflection',
    'rajyoga-open-eye-meditation',
    'tanden-breathing-serotonin',
    'wim-hof-breathing-inflammation',
    'zazen-zen-meditation-brain',
    'zen-koans-brain-cognition',
  ],
}

/** Breathing-aid reviews, round-up and duels translated 2026-10-07 — queued in every language. */
export const REVIEW_RELEASE_QUEUE: readonly { collection: 'reviews' | 'comparisons' | 'h2h'; slug: string }[] = [
  { collection: 'reviews', slug: 'ayo-sleep-tape' },
  { collection: 'reviews', slug: 'dream-recovery-mouth-tape' },
  { collection: 'reviews', slug: 'hostage-tape' },
  { collection: 'reviews', slug: 'nexcare-surgical-tape' },
  { collection: 'reviews', slug: 'sleep-strips-by-sleepright' },
  { collection: 'reviews', slug: 'somnifit-sleep-strips' },
  { collection: 'reviews', slug: 'somnifix' },
  { collection: 'reviews', slug: 'the-tape-co' },
  { collection: 'reviews', slug: 'breathe-right-original' },
  { collection: 'reviews', slug: 'intake-breathing' },
  { collection: 'reviews', slug: 'mute-nasal-dilator' },
  { collection: 'comparisons', slug: 'best-mouth-tape-nasal-breathing-2026' },
  { collection: 'h2h', slug: 'hostage-tape-vs-dream-recovery-mouth-tape' },
  { collection: 'h2h', slug: 'hostage-tape-vs-somnifix' },
  { collection: 'h2h', slug: 'hostage-tape-vs-intake-breathing' },
  { collection: 'h2h', slug: 'hostage-tape-vs-somnifix-vs-intake-breathing' },
  { collection: 'h2h', slug: 'intake-breathing-vs-breathe-right-original' },
  { collection: 'h2h', slug: 'intake-breathing-vs-mute-nasal-dilator' },
]

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`)
  d.setUTCDate(d.getUTCDate() + days)
  return d.toISOString().slice(0, 10)
}

const streams: { lang: string; collection: PublishCollection; slug: string }[][] = LANG_ORDER.map((lang) => [
  ...(ARTICLE_RELEASE_QUEUE[lang] ?? []).map((slug) => ({ lang, collection: 'articles' as PublishCollection, slug })),
  ...REVIEW_RELEASE_QUEUE.map((r) => ({ lang, collection: r.collection as PublishCollection, slug: r.slug })),
])

/** Round-robin across languages → one ordered site-wide list → dates by position. */
export const RELEASE_QUEUE_ENTRIES: PublishEntry[] = (() => {
  const order: { lang: string; collection: PublishCollection; slug: string }[] = []
  const longest = Math.max(...streams.map((s) => s.length))
  for (let i = 0; i < longest; i++) for (const s of streams) if (s[i]) order.push(s[i])
  return order.map((e, i) => ({ ...e, publishOn: addDays(QUEUE_START, Math.floor(i / PER_BATCH) * EVERY_DAYS) }))
})()
