/**
 * Build-time generator for ARTICLE_DATES (consumed by ArticlePage and
 * GlossaryTermPage to fill datePublished / dateModified in JSON-LD).
 *
 * Strategy: use git history when available (first commit = published,
 * last commit = modified). Falls back to file mtime when git history is
 * missing — e.g. shallow clone in CI or fresh worktree.
 *
 * Output: landing/src/data/article-dates.generated.ts
 *   export const ARTICLE_DATES: Record<string, { published: string; modified: string }>
 *
 * Cache: landing/scripts/.article-dates.cache.json
 *   Stores a fingerprint of the article + glossary files plus the last
 *   generated dates map. Skips the 136 git-log spawns when nothing has
 *   changed since the previous build — turns a ~50 second stage into
 *   a sub-second no-op for incremental rebuilds.
 *
 * Run order (npm run build):
 *   optimize-images -> article-dates -> tsc -> vite build -> prerender ...
 */
import { execSync } from 'child_process'
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'fs'
import { createHash } from 'crypto'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..', '..')
const articlesDir = join(__dirname, '..', 'src', 'data', 'articles')
const glossaryFile = join(__dirname, '..', 'src', 'data', 'glossary.ts')
const outFile = join(__dirname, '..', 'src', 'data', 'article-dates.generated.ts')
const cacheFile = join(__dirname, '.article-dates.cache.json')

/** Returns ISO timestamp string or null if git failed. */
function gitDate(filePath, mode) {
  try {
    const flag = mode === 'first' ? '--diff-filter=A --follow --reverse' : '-1'
    const cmd = `git log ${flag} --format=%aI -- "${filePath}"`
    const out = execSync(cmd, { cwd: repoRoot, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
      .split('\n')
      .filter(Boolean)
    if (out.length === 0) return null
    return mode === 'first' ? out[0] : out[0]
  } catch {
    return null
  }
}

function fileDates(filePath) {
  const published = gitDate(filePath, 'first')
  const modified = gitDate(filePath, 'last')
  if (published && modified) return { published, modified }
  // Fallback: filesystem mtime, same value for both fields.
  const mtime = statSync(filePath).mtime.toISOString()
  return { published: published ?? mtime, modified: modified ?? mtime }
}

const articleSlugs = readdirSync(articlesDir)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts' && f !== 'types.ts')
  .map((f) => f.replace(/\.ts$/, ''))

/** Quick fingerprint of every input that could change the generated map:
 *  - the sorted list of article slugs (catches add/remove)
 *  - the mtime + size of each article file and glossary.ts (catches edits
 *    even when git history hasn't picked them up yet)
 *  - the current git HEAD (catches new commits that change first/last dates) */
function inputFingerprint() {
  const h = createHash('sha1')
  h.update(articleSlugs.join('\n'))
  for (const slug of articleSlugs) {
    const p = join(articlesDir, slug + '.ts')
    try {
      const s = statSync(p)
      h.update(`${slug}:${s.mtimeMs}:${s.size}\n`)
    } catch {}
  }
  try {
    const g = statSync(glossaryFile)
    h.update(`__glossary:${g.mtimeMs}:${g.size}\n`)
  } catch {}
  try {
    const head = execSync('git rev-parse HEAD', { cwd: repoRoot, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
    h.update(`HEAD:${head}\n`)
  } catch {}
  return h.digest('hex')
}

const banner = `/**
 * AUTO-GENERATED by landing/scripts/article-dates.mjs.
 * Do not edit by hand. Regenerated on every \`npm run build\`.
 *
 * Maps article slug -> { published, modified } ISO timestamps for use in
 * JSON-LD Article schema. The special key __glossary holds the dates that
 * apply to every glossary term (the registry lives in one file).
 */
`

const fingerprint = inputFingerprint()

// Cache hit: nothing changed since last run AND the generated output still
// exists on disk. Skip the 136 git-log invocations entirely.
if (existsSync(cacheFile) && existsSync(outFile)) {
  try {
    const cache = JSON.parse(readFileSync(cacheFile, 'utf-8'))
    if (cache.fingerprint === fingerprint && cache.dates) {
      console.log(
        `[article-dates] cache hit — reusing ${articleSlugs.length} article dates (skipped ${articleSlugs.length * 2 + 2} git log spawns)`,
      )
      process.exit(0)
    }
  } catch {
    // Corrupt cache — fall through and regenerate.
  }
}

const dates = {}
for (const slug of articleSlugs) {
  dates[slug] = fileDates(join(articlesDir, slug + '.ts'))
}

// Glossary lives in a single TS file — all terms inherit its dates.
const glossaryDates = fileDates(glossaryFile)
dates.__glossary = glossaryDates

const body =
  banner +
  '\nexport const ARTICLE_DATES: Record<string, { published: string; modified: string }> = ' +
  JSON.stringify(dates, null, 2) +
  '\n'

writeFileSync(outFile, body)
writeFileSync(cacheFile, JSON.stringify({ fingerprint, dates }, null, 2))
console.log(
  `[article-dates] Generated ${outFile.replace(repoRoot + '/', '')} for ${articleSlugs.length} articles + glossary (cache updated)`,
)
