/**
 * Build-time generator: produces lightweight registries so the main client
 * bundle doesn't have to inline ~3 MB of article body markdown.
 *
 *   src/data/articles/articles-meta.generated.ts
 *     → array of every article with `content` / `howToSteps` stripped.
 *       Used by HomePage's ArticlesSection, ArticlesPage list, SitemapPage,
 *       and GlossaryTermPage's "related articles" view.
 *
 *   src/data/articles/term-articles.generated.ts
 *     → Record<glossaryTermSlug, articleSlug[]> precomputed by scanning each
 *       article's content for the term's title / slug. Replaces the runtime
 *       `getArticlesForTerm` content scan in GlossaryTermPage.
 *
 * The full registry (`src/data/articles/index.ts`) stays sync for the SSR
 * prerender + lazy-loaded ArticlePage chunk on the client. Both already live
 * outside the main bundle thanks to React.lazy in main.tsx.
 *
 * Runs as the first TS step of `npm run build`, before `tsc -b`.
 */
import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { articles } from '../src/data/articles'
import { glossaryTerms } from '../src/data/glossary'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = join(__dirname, '..', 'src', 'data', 'articles')
mkdirSync(outDir, { recursive: true })

const HEADER = `// AUTO-GENERATED by scripts/articles-meta.ts — do not edit by hand.\n// Regenerated on every \`npm run build\`.\n`

// ---------------------------------------------------------------------------
// 1) articles-meta.generated.ts — strip heavy fields (content, howToSteps).
// ---------------------------------------------------------------------------

const meta = articles.map((a) => {
  // Intentionally drop: content, howToSteps. Keep everything else so that
  // existing card / list / SEO meta consumers are a drop-in replacement.
  const { content: _c, howToSteps: _h, ...rest } = a
  void _c; void _h
  return rest
})

const metaSrc =
  HEADER +
  `import type { Article } from './types'\n\n` +
  `/** Article without body content — safe to ship in the main bundle. */\n` +
  `export type ArticleMeta = Omit<Article, 'content' | 'howToSteps'>\n\n` +
  `export const articlesMeta: ArticleMeta[] = ${JSON.stringify(meta, null, 2)}\n`

writeFileSync(join(outDir, 'articles-meta.generated.ts'), metaSrc)

// ---------------------------------------------------------------------------
// 2) term-articles.generated.ts — precompute glossary term → article slugs.
//    Mirrors the runtime logic of getArticlesForTerm() but pays the content
//    scan once at build instead of per-page-load (and per article).
// ---------------------------------------------------------------------------

const map: Record<string, string[]> = {}
for (const term of glossaryTerms) {
  const slugLower = term.slug.toLowerCase()
  const titleLower = term.title.toLowerCase()
  const slugAsWords = slugLower.replace(/-/g, ' ')
  const matched: string[] = []
  for (const a of articles) {
    if (a.relatedSlugs?.includes(term.slug)) {
      matched.push(a.slug)
      continue
    }
    const c = a.content.toLowerCase()
    if (c.includes(titleLower) || c.includes(slugAsWords)) {
      matched.push(a.slug)
    }
  }
  if (matched.length > 0) map[term.slug] = matched
}

const mapSrc =
  HEADER +
  `/** Glossary term slug → article slugs that mention the term. */\n` +
  `export const termArticleSlugs: Record<string, string[]> = ${JSON.stringify(map, null, 2)}\n`

writeFileSync(join(outDir, 'term-articles.generated.ts'), mapSrc)

console.log(
  `[articles-meta] generated meta (${meta.length} articles) + term-map (${Object.keys(map).length} terms)`,
)
