/**
 * Build-time generator for ARTICLE_DATES (consumed by ArticlePage and
 * GlossaryTermPage to fill datePublished / dateModified in JSON-LD).
 *
 * Strategy: use git history when available (first commit = published,
 * last commit = modified). Falls back to file mtime when git history is
 * missing — e.g. shallow clone in CI or fresh worktree.
 *
 * Output: landing/src/data/article-dates.generated.ts
 *   export const ARTICLE_DATES: Record<string, { published: string; modified: string }>
 *
 * Run order (npm run build):
 *   optimize-images -> article-dates -> tsc -> vite build -> prerender ...
 */
import { execSync } from 'child_process'
import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..', '..')
const articlesDir = join(__dirname, '..', 'src', 'data', 'articles')
const glossaryFile = join(__dirname, '..', 'src', 'data', 'glossary.ts')
const outFile = join(__dirname, '..', 'src', 'data', 'article-dates.generated.ts')

/** Returns ISO timestamp string or null if git failed. */
function gitDate(filePath, mode) {
  try {
    const flag = mode === 'first' ? '--diff-filter=A --follow --reverse' : '-1'
    const cmd = `git log ${flag} --format=%aI -- "${filePath}"`
    const out = execSync(cmd, { cwd: repoRoot, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
      .split('\n')
      .filter(Boolean)
    if (out.length === 0) return null
    return mode === 'first' ? out[0] : out[0]
  } catch {
    return null
  }
}

function fileDates(filePath) {
  const published = gitDate(filePath, 'first')
  const modified = gitDate(filePath, 'last')
  if (published && modified) return { published, modified }
  // Fallback: filesystem mtime, same value for both fields.
  const mtime = statSync(filePath).mtime.toISOString()
  return { published: published ?? mtime, modified: modified ?? mtime }
}

const articleSlugs = readdirSync(articlesDir)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts' && f !== 'types.ts')
  .map((f) => f.replace(/\.ts$/, ''))

const dates = {}
for (const slug of articleSlugs) {
  dates[slug] = fileDates(join(articlesDir, slug + '.ts'))
}

// Glossary lives in a single TS file — all terms inherit its dates.
const glossaryDates = fileDates(glossaryFile)
dates.__glossary = glossaryDates

const banner = `/**
 * AUTO-GENERATED by landing/scripts/article-dates.mjs.
 * Do not edit by hand. Regenerated on every \`npm run build\`.
 *
 * Maps article slug -> { published, modified } ISO timestamps for use in
 * JSON-LD Article schema. The special key __glossary holds the dates that
 * apply to every glossary term (the registry lives in one file).
 */
`

const body =
  banner +
  '\nexport const ARTICLE_DATES: Record<string, { published: string; modified: string }> = ' +
  JSON.stringify(dates, null, 2) +
  '\n'

writeFileSync(outFile, body)
console.log(
  `[article-dates] Generated ${outFile.replace(repoRoot + '/', '')} for ${articleSlugs.length} articles + glossary`,
)
