/**
 * Generates public/embed/onda-hrv-widget.js (the dependency-free embed widget)
 * from src/data/hrv-norms.ts, so the widget never carries a hand-copied table.
 *
 *   npx tsx scripts/build-hrv-widget.ts           # write the file
 *   npx tsx scripts/build-hrv-widget.ts --check   # exit 1 if the file is stale
 *
 * Runs in `npm run build` before vite copies public/. Bump HRV_WIDGET_VERSION
 * (src/data/hrv-widget-version.ts) when data or wording change: the embed snippet
 * on /tools/hrv loads `onda-hrv-widget.js?v=<version>`; the bare URL keeps working.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { HRV_AGE_POINTS, HRV_COMPARISON_DISCLAIMER, HRV_DEVICE_NOTE, HRV_MAX_COMPARED_AGE, HRV_NO_COMPARISON_NOTE, HRV_POSITION_TEXT, HRV_VERDICT_TEXT } from '../src/data/hrv-norms'
import { HRV_WIDGET_VERSION } from '../src/data/hrv-widget-version'

const OUT = join(process.cwd(), 'public', 'embed', 'onda-hrv-widget.js')

const points = HRV_AGE_POINTS.map(
  (p) =>
    `    { min: ${p.minAge}, max: ${p.maxAge}, label: '${p.label}', female: [${p.female.p25}, ${p.female.p50}, ${p.female.p75}], male: [${p.male.p25}, ${p.male.p50}, ${p.male.p75}] }`,
).join(',\n')

const js = `/*!
 * ONDA Life — HRV by age widget (embeddable, dependency-free) — v${HRV_WIDGET_VERSION}
 * GENERATED by scripts/build-hrv-widget.ts from src/data/hrv-norms.ts — do not edit.
 * Enter age, sex and morning RMSSD → comparison with the published distribution
 * among about 8 million Fitbit users of the nearest age group (Natarajan 2020,
 * Lancet Digital Health, Supplementary Table S3, 6–7 a.m.). A comparison with
 * users of one device, not a medical norm. No interpolation between age groups.
 * Sex "Prefer not to say" shows the comparison with both groups, no single verdict.
 * Ages above ${HRV_MAX_COMPARED_AGE}: no verdict (the data end at 61); the oldest group is shown for information.
 *
 * Usage on any page:
 *   <div data-onda-hrv></div>
 *   <script src="https://onda-life.com/embed/onda-hrv-widget.js?v=${HRV_WIDGET_VERSION}" defer></script>
 *
 * Renders in the host page's light DOM with scoped \`ondahrv-\` classes, so the
 * "Powered by ONDA Life" attribution link is a normal, crawlable link on your
 * page. Educational only — not medical advice. MIT licensed.
 * Source: https://github.com/yamius/onda-hrv-widget
 */
(function () {
  'use strict';
  var VERSION = '${HRV_WIDGET_VERSION}';
  var SITE = 'https://onda-life.com';
  var TOOL_URL = SITE + '/tools/hrv?utm_source=widget&utm_medium=embed';

  // RMSSD (ms) between 6 and 7 a.m. among Fitbit users: [p25, median, p75].
  // Natarajan A et al. Lancet Digit Health 2020;2(12):e650–e657, Table S3.
  // Fitbit-authored and Fitbit-funded. Distribution among one device's users.
  var POINTS = [
${points}
  ];
  var VERDICT = ${JSON.stringify(HRV_VERDICT_TEXT)};
  var POSITION = ${JSON.stringify(HRV_POSITION_TEXT)};
  var DISCLAIMER = ${JSON.stringify(HRV_COMPARISON_DISCLAIMER)};
  var DEVICE_NOTE = ${JSON.stringify(HRV_DEVICE_NOTE)};
  var MAX_COMPARED_AGE = ${HRV_MAX_COMPARED_AGE};
  var NO_COMPARISON = ${JSON.stringify(HRV_NO_COMPARISON_NOTE)};
  var VERDICT_COLOR = { lower: '#fbbf24', middle: '#22d3ee', higher: '#34d399' };

  // Nearest age group by distance to its two-year span; a tie goes to the younger group.
  function nearest(age) {
    var best = POINTS[0], bestD = Infinity;
    for (var i = 0; i < POINTS.length; i++) {
      var p = POINTS[i];
      var d = age < p.min ? p.min - age : age > p.max ? age - p.max : 0;
      if (d < bestD) { best = p; bestD = d; }
    }
    return best;
  }
  function interpret(age, sex, rmssd) {
    var p = nearest(age), q = p[sex];
    var v = rmssd < q[0] ? 'lower' : rmssd > q[2] ? 'higher' : 'middle';
    return { point: p, q: q, verdict: v };
  }

  var STYLE_ID = 'ondahrv-styles';
  var CSS =
    '.ondahrv{box-sizing:border-box;max-width:420px;margin:0 auto;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:#0a1018;color:#fff;padding:20px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;line-height:1.5}' +
    '.ondahrv *{box-sizing:border-box}' +
    '.ondahrv__k{font:600 11px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.15em;text-transform:uppercase;color:rgba(34,211,238,.8);margin-bottom:12px}' +
    '.ondahrv__lead{font:400 12px/1.5 ui-monospace,monospace;color:rgba(255,255,255,.5);margin:0 0 16px}' +
    '.ondahrv__row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-bottom:16px}' +
    '.ondahrv__lab{display:block}' +
    '.ondahrv__lab span{display:block;font:600 10px/1 ui-monospace,monospace;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.5);margin-bottom:6px}' +
    '.ondahrv__in{width:100%;border:1px solid rgba(255,255,255,.15);border-radius:10px;background:rgba(0,0,0,.3);color:#fff;padding:9px 10px;font:400 16px ui-monospace,monospace;outline:none}' +
    '.ondahrv__in:focus{border-color:rgba(52,211,153,.6)}' +
    '.ondahrv__out{border:1px solid rgba(255,255,255,.1);border-radius:10px;background:rgba(255,255,255,.05);padding:12px}' +
    '.ondahrv__tier{font:700 16px/1.3 system-ui,sans-serif}' +
    '.ondahrv__note{margin:8px 0 0;font:400 11px/1.5 ui-monospace,monospace;color:rgba(255,255,255,.55)}' +
    '.ondahrv__disc{margin:8px 0 0;font:400 11px/1.5 ui-monospace,monospace;color:rgba(255,255,255,.75)}' +
    '.ondahrv__hint{font:400 12px ui-monospace,monospace;color:rgba(255,255,255,.4);margin:0}' +
    '.ondahrv__by{margin-top:16px;text-align:center}' +
    '.ondahrv__by a{font:400 10px ui-monospace,monospace;color:rgba(255,255,255,.4);text-decoration:none}' +
    '.ondahrv__by a:hover{color:#34d399}' +
    '.ondahrv__by b{color:#34d399;font-weight:600}.ondahrv__by i{color:#22d3ee;font-style:normal}';

  function injectStyle() {
    if (document.getElementById(STYLE_ID)) return;
    var s = document.createElement('style');
    s.id = STYLE_ID; s.textContent = CSS;
    document.head.appendChild(s);
  }

  function mount(el) {
    if (el.getAttribute('data-onda-hrv-ready')) return;
    el.setAttribute('data-onda-hrv-ready', VERSION);

    var root = document.createElement('div');
    root.className = 'ondahrv';
    root.innerHTML =
      '<div class="ondahrv__k">HRV by age</div>' +
      '<p class="ondahrv__lead">Enter your age, sex and morning RMSSD to compare it with about 8 million Fitbit users of your age (Natarajan 2020).</p>' +
      '<div class="ondahrv__row">' +
        '<label class="ondahrv__lab"><span>Age</span><input class="ondahrv__in" data-f="age" type="number" inputmode="numeric" min="18" max="100" value="35"></label>' +
        '<label class="ondahrv__lab"><span>Sex</span><select class="ondahrv__in" data-f="sex"><option value="female">Woman</option><option value="male">Man</option><option value="unspecified">Prefer not to say</option></select></label>' +
        '<label class="ondahrv__lab"><span>RMSSD (ms)</span><input class="ondahrv__in" data-f="rmssd" type="number" inputmode="numeric" min="1" max="250" value="45"></label>' +
      '</div>' +
      '<div data-slot="out"></div>' +
      '<div class="ondahrv__by">' +
        '<a href="' + TOOL_URL + '" target="_blank" rel="noopener">Powered by <b>ONDA</b> <i>Life</i> — HRV Calculator by Age →</a>' +
      '</div>';
    el.appendChild(root);

    var out = root.querySelector('[data-slot="out"]');
    var ageEl = root.querySelector('[data-f="age"]');
    var sexEl = root.querySelector('[data-f="sex"]');
    var rmssdEl = root.querySelector('[data-f="rmssd"]');

    function render() {
      var a = parseInt(ageEl.value, 10), r = parseInt(rmssdEl.value, 10), sex = sexEl.value === 'male' || sexEl.value === 'unspecified' ? sexEl.value : 'female';
      if (!a || a < 18 || a > 100 || !r || r < 1 || r > 250) {
        out.innerHTML = '<p class="ondahrv__hint">Enter age (18–100) and RMSSD (1–250 ms).</p>';
        return;
      }
      if (a > MAX_COMPARED_AGE) {
        var groups = sex === 'unspecified' ? ['female', 'male'] : [sex];
        var info = '';
        for (var g = 0; g < groups.length; g++) {
          var x = interpret(a, groups[g], r);
          info += '<p class="ondahrv__note">For information only — Fitbit ' + (groups[g] === 'male' ? 'men' : 'women') + ' aged ' + x.point.label +
            ': middle half ' + x.q[0] + '–' + x.q[2] + ' ms, median ' + x.q[1] + ' ms (RMSSD, 6–7 a.m.).</p>';
        }
        out.innerHTML =
          '<div class="ondahrv__out">' +
            '<p class="ondahrv__disc">' + NO_COMPARISON + '</p>' + info +
            '<p class="ondahrv__disc">' + DEVICE_NOTE + '</p>' +
            '<p class="ondahrv__disc">' + DISCLAIMER + '</p>' +
          '</div>';
        return;
      }
      var edge = a < POINTS[0].min ? ' The data start at age 20.' : a > POINTS[POINTS.length - 1].max ? ' The data stop at age 61.' : '';
      if (sex === 'unspecified') {
        var f = interpret(a, 'female', r), m = interpret(a, 'male', r);
        var line = function (word, x) {
          return '<p class="ondahrv__disc">Compared with Fitbit ' + word + ' aged ' + x.point.label + ': your value is ' + POSITION[x.verdict] +
            ' (middle half ' + x.q[0] + '–' + x.q[2] + ' ms, median ' + x.q[1] + ' ms).</p>';
        };
        out.innerHTML =
          '<div class="ondahrv__out">' + line('women', f) + line('men', m) +
            '<p class="ondahrv__note">RMSSD, 6–7 a.m.' + edge + '</p>' +
            '<p class="ondahrv__disc">' + DISCLAIMER + '</p>' +
            '<p class="ondahrv__disc">' + DEVICE_NOTE + '</p>' +
          '</div>';
        return;
      }
      var res = interpret(a, sex, r);
      out.innerHTML =
        '<div class="ondahrv__out">' +
          '<div class="ondahrv__tier" style="color:' + VERDICT_COLOR[res.verdict] + '">' + VERDICT[res.verdict] + '</div>' +
          '<p class="ondahrv__note">Compared with Fitbit ' + (sex === 'male' ? 'men' : 'women') + ' aged ' + res.point.label +
            ': middle half ' + res.q[0] + '–' + res.q[2] + ' ms, median ' + res.q[1] + ' ms (RMSSD, 6–7 a.m.).' + edge + '</p>' +
          '<p class="ondahrv__disc">' + DISCLAIMER + '</p>' +
          '<p class="ondahrv__disc">' + DEVICE_NOTE + '</p>' +
        '</div>';
    }
    ageEl.addEventListener('input', render);
    sexEl.addEventListener('change', render);
    rmssdEl.addEventListener('input', render);
    render();
  }

  function init() {
    injectStyle();
    var nodes = document.querySelectorAll('[data-onda-hrv]');
    for (var i = 0; i < nodes.length; i++) mount(nodes[i]);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();

  // Expose a manual mount for SPA / dynamic insertion.
  window.OndaHrvWidget = { mount: mount, init: init, version: VERSION };
})();
`

if (process.argv.includes('--check')) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : ''
  if (cur !== js) {
    console.error('[hrv-widget] public/embed/onda-hrv-widget.js is stale — run npx tsx scripts/build-hrv-widget.ts')
    process.exit(1)
  }
  console.log('[hrv-widget] up to date')
} else {
  writeFileSync(OUT, js)
  console.log(`[hrv-widget] wrote public/embed/onda-hrv-widget.js (v${HRV_WIDGET_VERSION}, ${HRV_AGE_POINTS.length} age groups)`)
}
