/**
 * Splits article content so the browser never downloads more than one article.
 *
 * Authoring sources stay unchanged:
 *   - EN articles:   src/data/articles/*.ts (+ ARTICLE_FAQ in src/data/article-faq.ts)
 *   - translations:  public/locales/<lang>/articles.json → bodies.<slug>
 * The prerender (Node) keeps reading those full sources. This script writes the
 * browser-side artifacts:
 *
 *   src/generated/article-catalog.ts          EN metadata only (no body) — lists, hubs, cards
 *   src/generated/term-articles.ts            glossary term → article slugs (was a runtime full-text scan)
 *   src/generated/i18n/<lang>/articles.json   locale namespace with bodies cut to title/description/imageAlt
 *   public/_content/articles/<lang>/<slug>.json   one article's full body (EN: content, howTo, FAQ…;
 *                                                 other langs: that slug's bodies entry)
 *
 * Run automatically by `npm run build` and `npm run dev`. Everything it writes is
 * gitignored — edit the sources, never these files.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { articles, type Article } from '../src/data/articles'
import { ARTICLE_FAQ } from '../src/data/article-faq'
import { glossaryTerms } from '../src/data/glossary'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const GEN = join(root, 'src', 'generated')
const CONTENT = join(root, 'public', '_content', 'articles')
const LOCALES = join(root, 'public', 'locales')

/** Fields every list/card/hub needs. Everything else is body and ships per article. */
const CATALOG_KEYS = ['slug', 'title', 'description', 'category', 'image', 'imageAlt', 'imageTitle'] as const
export type CatalogKey = (typeof CATALOG_KEYS)[number]

const pick = <T extends object, K extends keyof T>(o: T, keys: readonly K[]) =>
  Object.fromEntries(keys.filter((k) => o[k] !== undefined).map((k) => [k, o[k]])) as Pick<T, K>

rmSync(CONTENT, { recursive: true, force: true })
rmSync(join(GEN, 'i18n'), { recursive: true, force: true })
mkdirSync(join(CONTENT, 'en'), { recursive: true })
mkdirSync(GEN, { recursive: true })

// ── EN: catalog + one body file per article ────────────────────────────────
const catalog = articles.map((a) => pick(a, CATALOG_KEYS as unknown as (keyof Article)[]))
let enBytes = 0
for (const a of articles) {
  const body: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(a)) if (!(CATALOG_KEYS as readonly string[]).includes(k)) body[k] = v
  const faq = ARTICLE_FAQ[a.slug]
  if (faq?.length) body.faq = faq
  const json = JSON.stringify(body)
  enBytes += json.length
  writeFileSync(join(CONTENT, 'en', `${a.slug}.json`), json)
}
writeFileSync(
  join(GEN, 'article-catalog.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `// EN article metadata without bodies. Full text: public/_content/articles/<lang>/<slug>.json\n` +
    `import type { Article } from '../data/articles/types'\n` +
    `export type ArticleMeta = Pick<Article, ${CATALOG_KEYS.map((k) => `'${k}'`).join(' | ')}>\n` +
    `export const ARTICLE_CATALOG: ArticleMeta[] = ${JSON.stringify(catalog)}\n`,
)

// ── Glossary term → articles (same rule the old runtime scan used) ─────────
const termArticles: Record<string, string[]> = {}
for (const term of glossaryTerms) {
  const slugLower = term.slug.toLowerCase().replace(/-/g, ' ')
  const titleLower = term.title.toLowerCase()
  const hits = articles
    .filter((a) => {
      if (a.relatedSlugs?.includes(term.slug)) return true
      const c = a.content.toLowerCase()
      return c.includes(titleLower) || c.includes(slugLower)
    })
    .map((a) => a.slug)
  if (hits.length) termArticles[term.slug] = hits
}
writeFileSync(
  join(GEN, 'term-articles.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `export const TERM_ARTICLES: Record<string, string[]> = ${JSON.stringify(termArticles)}\n`,
)

// ── Light glossary index (link injection + "related terms" cards need no term bodies) ──
const glossaryIndex = glossaryTerms.map((t) => ({ slug: t.slug, title: t.title, shortDescription: t.shortDescription }))
writeFileSync(
  join(GEN, 'glossary-index.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `export interface GlossaryIndexEntry { slug: string; title: string; shortDescription: string }\n` +
    `export const GLOSSARY_INDEX: GlossaryIndexEntry[] = ${JSON.stringify(glossaryIndex)}\n`,
)

// ── Translations: light namespace + one body file per translated article ──
const INDEX_BODY_KEYS = ['title', 'description', 'imageAlt'] as const
const report: string[] = []
for (const lang of readdirSync(LOCALES)) {
  if (lang === 'en') continue
  let file: { bodies?: Record<string, Record<string, unknown>> } & Record<string, unknown>
  try {
    file = JSON.parse(readFileSync(join(LOCALES, lang, 'articles.json'), 'utf-8'))
  } catch {
    continue
  }
  const bodies = file.bodies ?? {}
  mkdirSync(join(CONTENT, lang), { recursive: true })
  for (const [slug, body] of Object.entries(bodies)) {
    writeFileSync(join(CONTENT, lang, `${slug}.json`), JSON.stringify(body))
  }
  const light = {
    ...file,
    bodies: Object.fromEntries(Object.entries(bodies).map(([slug, b]) => [slug, pick(b, INDEX_BODY_KEYS as unknown as string[])])),
  }
  mkdirSync(join(GEN, 'i18n', lang), { recursive: true })
  const lightJson = JSON.stringify(light)
  writeFileSync(join(GEN, 'i18n', lang, 'articles.json'), lightJson)
  report.push(`${lang}:${Object.keys(bodies).length}/${Math.round(lightJson.length / 1024)}K`)
}

// ── Light glossary namespace for article pages (related-term cards: title + shortDescription).
// Registered under the 'glossary' namespace as 'glossary-light' (src/i18n.ts); glossary pages
// still load the full file.
for (const lang of readdirSync(LOCALES)) {
  if (lang === 'en') continue
  let file: { bodies?: Record<string, Record<string, unknown>> }
  try {
    file = JSON.parse(readFileSync(join(LOCALES, lang, 'glossary.json'), 'utf-8'))
  } catch {
    continue
  }
  const light = {
    bodies: Object.fromEntries(
      Object.entries(file.bodies ?? {}).map(([slug, b]) => [slug, pick(b, ['title', 'shortDescription'])]),
    ),
  }
  mkdirSync(join(GEN, 'i18n', lang), { recursive: true })
  writeFileSync(join(GEN, 'i18n', lang, 'glossary-light.json'), JSON.stringify(light))
}

console.log(
  `[article-chunks] en:${articles.length} bodies (${Math.round(enBytes / 1024)}K total), catalog ${Math.round(JSON.stringify(catalog).length / 1024)}K, ` +
    `terms→articles ${Object.keys(termArticles).length} | locales ${report.join(' ')}`,
)
