/**
 * Splits article content so the browser never downloads more than one article.
 *
 * Authoring sources stay unchanged:
 *   - EN articles:   src/data/articles/*.ts (+ ARTICLE_FAQ in src/data/article-faq.ts)
 *   - translations:  public/locales/<lang>/articles.json → bodies.<slug>
 * The prerender (Node) keeps reading those full sources. This script writes the
 * browser-side artifacts:
 *
 *   src/generated/article-catalog.ts          EN metadata only (no body) — lists, hubs, cards
 *   src/generated/term-articles.ts            glossary term → article slugs (was a runtime full-text scan)
 *   src/generated/i18n/<lang>/articles.json   locale namespace with bodies cut to title/description/imageAlt
 *   public/_content/articles/<lang>/<slug>.json   one article's full body (EN: content, howTo, FAQ…;
 *                                                 other langs: that slug's bodies entry)
 *
 * Run automatically by `npm run build` and `npm run dev`. Everything it writes is
 * gitignored — edit the sources, never these files.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { articles, type Article } from '../src/data/articles'
import { ARTICLE_FAQ } from '../src/data/article-faq'
import { ARTICLE_CITATIONS } from '../src/data/article-citations'
import { glossaryTerms } from '../src/data/glossary'
import { ALL_REVIEWS, ALL_COMPARISONS } from '../src/data/reviews'
import { ALL_HEAD_TO_HEADS } from '../src/data/reviews/head-to-head'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const GEN = join(root, 'src', 'generated')
const CONTENT = join(root, 'public', '_content', 'articles')
const LOCALES = join(root, 'public', 'locales')

/** Fields every list/card/hub needs. Everything else is body and ships per article. */
const CATALOG_KEYS = ['slug', 'title', 'description', 'category', 'image', 'imageAlt', 'imageTitle'] as const
export type CatalogKey = (typeof CATALOG_KEYS)[number]

const pick = <T extends object, K extends keyof T>(o: T, keys: readonly K[]) =>
  Object.fromEntries(keys.filter((k) => o[k] !== undefined).map((k) => [k, o[k]])) as Pick<T, K>

rmSync(join(root, 'public', '_content'), { recursive: true, force: true })
rmSync(join(GEN, 'i18n'), { recursive: true, force: true })
mkdirSync(join(CONTENT, 'en'), { recursive: true })
mkdirSync(GEN, { recursive: true })

// ── EN: catalog + one body file per article ────────────────────────────────
const catalog = articles.map((a) => pick(a, CATALOG_KEYS as unknown as (keyof Article)[]))
let enBytes = 0
for (const a of articles) {
  const body: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(a)) if (!(CATALOG_KEYS as readonly string[]).includes(k)) body[k] = v
  const faq = ARTICLE_FAQ[a.slug]
  if (faq?.length) body.faq = faq
  const cites = ARTICLE_CITATIONS[a.slug]
  if (cites?.length) body.citations = cites
  const json = JSON.stringify(body)
  enBytes += json.length
  writeFileSync(join(CONTENT, 'en', `${a.slug}.json`), json)
}
writeFileSync(
  join(GEN, 'article-catalog.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `// EN article metadata without bodies. Full text: public/_content/articles/<lang>/<slug>.json\n` +
    `import type { Article } from '../data/articles/types'\n` +
    `export type ArticleMeta = Pick<Article, ${CATALOG_KEYS.map((k) => `'${k}'`).join(' | ')}>\n` +
    `export const ARTICLE_CATALOG: ArticleMeta[] = ${JSON.stringify(catalog)}\n`,
)

// ── Glossary term → articles (same rule the old runtime scan used) ─────────
const termArticles: Record<string, string[]> = {}
for (const term of glossaryTerms) {
  const slugLower = term.slug.toLowerCase().replace(/-/g, ' ')
  const titleLower = term.title.toLowerCase()
  const hits = articles
    .filter((a) => {
      if (a.relatedSlugs?.includes(term.slug)) return true
      const c = a.content.toLowerCase()
      return c.includes(titleLower) || c.includes(slugLower)
    })
    .map((a) => a.slug)
  if (hits.length) termArticles[term.slug] = hits
}
writeFileSync(
  join(GEN, 'term-articles.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `export const TERM_ARTICLES: Record<string, string[]> = ${JSON.stringify(termArticles)}\n`,
)

// ── Glossary: light index + one body (content) file per term ─────────────
// Pages list/label/link terms from the index; only the term page loads a body.
const glossaryIndex = glossaryTerms.map((t) => ({
  slug: t.slug,
  title: t.title,
  category: t.category,
  shortDescription: t.shortDescription,
  ...(t.relatedSlugs?.length ? { relatedSlugs: t.relatedSlugs } : {}),
}))
mkdirSync(join(root, 'public', '_content', 'glossary', 'en'), { recursive: true })
for (const t of glossaryTerms) {
  writeFileSync(join(root, 'public', '_content', 'glossary', 'en', `${t.slug}.json`), JSON.stringify({ content: t.content }))
}
writeFileSync(
  join(GEN, 'glossary-index.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.
` +
    `// Glossary terms without their content (full text: public/_content/glossary/<lang>/<slug>.json).
` +
    `export interface GlossaryIndexEntry { slug: string; title: string; category: string; shortDescription: string; relatedSlugs?: string[] }
` +
    `export const GLOSSARY_INDEX: GlossaryIndexEntry[] = ${JSON.stringify(glossaryIndex)}
`,
)

// ── Translations: light namespace + one body file per translated article ──
const INDEX_BODY_KEYS = ['title', 'description', 'imageAlt'] as const
const report: string[] = []
for (const lang of readdirSync(LOCALES)) {
  if (lang === 'en') continue
  let file: { bodies?: Record<string, Record<string, unknown>> } & Record<string, unknown>
  try {
    file = JSON.parse(readFileSync(join(LOCALES, lang, 'articles.json'), 'utf-8'))
  } catch {
    continue
  }
  const bodies = file.bodies ?? {}
  mkdirSync(join(CONTENT, lang), { recursive: true })
  for (const [slug, body] of Object.entries(bodies)) {
    writeFileSync(join(CONTENT, lang, `${slug}.json`), JSON.stringify(body))
  }
  const light = {
    ...file,
    bodies: Object.fromEntries(Object.entries(bodies).map(([slug, b]) => [slug, pick(b, INDEX_BODY_KEYS as unknown as string[])])),
  }
  mkdirSync(join(GEN, 'i18n', lang), { recursive: true })
  const lightJson = JSON.stringify(light)
  writeFileSync(join(GEN, 'i18n', lang, 'articles.json'), lightJson)
  report.push(`${lang}:${Object.keys(bodies).length}/${Math.round(lightJson.length / 1024)}K`)
}

// ── Localized glossary: light namespace (UI strings + title/shortDescription per
// term) and one body file per translated term. Used for BOTH 'glossary' and
// 'glossary-light' in the browser (src/i18n.ts); the term page fetches its body.
for (const lang of readdirSync(LOCALES)) {
  if (lang === 'en') continue
  let file: { bodies?: Record<string, Record<string, unknown>> } & Record<string, unknown>
  try {
    file = JSON.parse(readFileSync(join(LOCALES, lang, 'glossary.json'), 'utf-8'))
  } catch {
    continue
  }
  const bodies = file.bodies ?? {}
  if (Object.keys(bodies).length) mkdirSync(join(root, 'public', '_content', 'glossary', lang), { recursive: true })
  for (const [slug, body] of Object.entries(bodies)) {
    writeFileSync(join(root, 'public', '_content', 'glossary', lang, `${slug}.json`), JSON.stringify(body))
  }
  const light = {
    ...file,
    bodies: Object.fromEntries(Object.entries(bodies).map(([slug, b]) => [slug, pick(b, ['title', 'shortDescription'])])),
  }
  mkdirSync(join(GEN, 'i18n', lang), { recursive: true })
  writeFileSync(join(GEN, 'i18n', lang, 'glossary.json'), JSON.stringify(light))
}

// ── Reviews / comparisons / head-to-heads: catalogs + one body per entry ────
// Catalogs keep EVERY entry (incl. date-gated ones, with publishOn) so the
// browser applies the same publishOn filter the data modules apply.
const REVIEW_BODY_KEYS = ['content', 'faq', 'references', 'summary', 'pros', 'cons', 'testNote', 'scores'] as const
const COMPARISON_BODY_KEYS = ['content', 'faq', 'intro'] as const
const H2H_BODY_KEYS = ['content', 'faq', 'intro', 'axes', 'verdict'] as const

function splitCollection<T extends { slug: string }>(
  name: 'reviews' | 'comparisons' | 'h2h',
  items: T[],
  bodyKeys: readonly string[],
  metaFix: (meta: Record<string, unknown>, item: T) => void = () => {},
) {
  mkdirSync(join(root, 'public', '_content', name, 'en'), { recursive: true })
  const metas: Record<string, unknown>[] = []
  for (const item of items) {
    const meta: Record<string, unknown> = {}
    const body: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(item)) (bodyKeys.includes(k) ? body : meta)[k] = v
    metaFix(meta, item)
    metas.push(meta)
    writeFileSync(join(root, 'public', '_content', name, 'en', `${item.slug}.json`), JSON.stringify(body))
  }
  return metas
}

// Review cards/lists compare scores by number only — the per-criterion notes ship in the body.
const reviewMetas = splitCollection('reviews', ALL_REVIEWS, REVIEW_BODY_KEYS, (meta, r) => {
  meta.scores = r.scores.map((s) => ({ criterionId: s.criterionId, score: s.score }))
})
const comparisonMetas = splitCollection('comparisons', ALL_COMPARISONS, COMPARISON_BODY_KEYS)
const h2hMetas = splitCollection('h2h', ALL_HEAD_TO_HEADS, H2H_BODY_KEYS)
writeFileSync(
  join(GEN, 'review-catalog.ts'),
  `// AUTO-GENERATED by scripts/generate-article-chunks.ts — do not edit.\n` +
    `// Review/comparison/head-to-head metadata without long bodies (full text: public/_content/<collection>/<lang>/<slug>.json).\n` +
    `import type { ToolReview, Comparison, HeadToHead, CriterionScore } from '../data/reviews/types'\n` +
    `export type ReviewMeta = Omit<ToolReview, ${REVIEW_BODY_KEYS.map((k) => `'${k}'`).join(' | ')}> & { scores: Omit<CriterionScore, 'note'>[] }\n` +
    `export type ComparisonMeta = Omit<Comparison, ${COMPARISON_BODY_KEYS.map((k) => `'${k}'`).join(' | ')}>\n` +
    `export type HeadToHeadMeta = Omit<HeadToHead, ${H2H_BODY_KEYS.map((k) => `'${k}'`).join(' | ')}>\n` +
    `export const REVIEW_CATALOG: ReviewMeta[] = ${JSON.stringify(reviewMetas)}\n` +
    `export const COMPARISON_CATALOG: ComparisonMeta[] = ${JSON.stringify(comparisonMetas)}\n` +
    `export const H2H_CATALOG: HeadToHeadMeta[] = ${JSON.stringify(h2hMetas)}\n`,
)

// Localized reviews namespace: light index + one body file per translated entry.
const REVIEW_LIGHT: Record<string, { col: 'reviews' | 'comparisons' | 'h2h'; keep: string[] }> = {
  bodies: { col: 'reviews', keep: ['verdict', 'description', 'bestFor'] },
  comparisons: { col: 'comparisons', keep: ['title', 'description'] },
  headToHeads: { col: 'h2h', keep: ['title', 'description', 'bestForA', 'bestForB'] },
}
const reviewReport: string[] = []
for (const lang of readdirSync(LOCALES)) {
  if (lang === 'en') continue
  let file: Record<string, unknown>
  try {
    file = JSON.parse(readFileSync(join(LOCALES, lang, 'reviews.json'), 'utf-8'))
  } catch {
    continue
  }
  const light: Record<string, unknown> = { ...file }
  let n = 0
  for (const [top, { col, keep }] of Object.entries(REVIEW_LIGHT)) {
    const entries = (file[top] ?? {}) as Record<string, Record<string, unknown>>
    if (!Object.keys(entries).length) continue
    mkdirSync(join(root, 'public', '_content', col, lang), { recursive: true })
    for (const [slug, body] of Object.entries(entries)) {
      writeFileSync(join(root, 'public', '_content', col, lang, `${slug}.json`), JSON.stringify(body))
      n++
    }
    light[top] = Object.fromEntries(Object.entries(entries).map(([slug, b]) => [slug, pick(b, keep)]))
  }
  mkdirSync(join(GEN, 'i18n', lang), { recursive: true })
  const lightJson = JSON.stringify(light)
  writeFileSync(join(GEN, 'i18n', lang, 'reviews.json'), lightJson)
  reviewReport.push(`${lang}:${n}/${Math.round(lightJson.length / 1024)}K`)
}
console.log(
  `[review-chunks] reviews ${reviewMetas.length}, comparisons ${comparisonMetas.length}, h2h ${h2hMetas.length}, ` +
    `catalog ${Math.round(readFileSync(join(GEN, 'review-catalog.ts'), 'utf-8').length / 1024)}K | locales ${reviewReport.join(' ')}`,
)

// ── Leak sentinels for scripts/check-budget.mjs ────────────────────────────
// Plain-text snippets taken from inside several bodies of every collection. If
// any of them shows up in a browser JS chunk, a full registry got bundled again.
function snippet(text: string | undefined): string | null {
  if (!text) return null
  const m = text.slice(Math.floor(text.length / 3)).match(/[A-Za-z][A-Za-z ,]{44,}[A-Za-z]/)
  return m ? m[0].slice(0, 45) : null
}
function localSnippet(text: unknown): string | null {
  if (typeof text !== 'string') return null
  const m = text.slice(Math.floor(text.length / 3)).match(/[\p{L}][\p{L} ,]{34,}[\p{L}]/u)
  return m ? m[0].slice(0, 35) : null
}
const sentinels: { collection: string; text: string }[] = []
const every = <T,>(arr: T[], n: number) => arr.filter((_, i) => i % Math.max(1, Math.floor(arr.length / n)) === 0).slice(0, n)
for (const a of every(articles, 4)) { const t = snippet(a.content); if (t) sentinels.push({ collection: 'articles/en', text: t }) }
for (const r of every(ALL_REVIEWS, 3)) { const t = snippet(r.content); if (t) sentinels.push({ collection: 'reviews/en', text: t }) }
for (const h of every(ALL_HEAD_TO_HEADS, 3)) { const t = snippet(h.content); if (t) sentinels.push({ collection: 'h2h/en', text: t }) }
for (const g of every(glossaryTerms, 3)) { const t = snippet(g.content); if (t) sentinels.push({ collection: 'glossary/en', text: t }) }
for (const lang of ['ru', 'es', 'de']) {
  try {
    const bodies = JSON.parse(readFileSync(join(LOCALES, lang, 'articles.json'), 'utf-8')).bodies ?? {}
    for (const b of every(Object.values(bodies) as Record<string, unknown>[], 2)) {
      const t = localSnippet(b.content)
      if (t) sentinels.push({ collection: `articles/${lang}`, text: t })
    }
  } catch { /* locale without articles */ }
}
writeFileSync(join(GEN, 'content-sentinels.json'), JSON.stringify(sentinels, null, 1))

console.log(
  `[article-chunks] en:${articles.length} bodies (${Math.round(enBytes / 1024)}K total), catalog ${Math.round(JSON.stringify(catalog).length / 1024)}K, ` +
    `terms→articles ${Object.keys(termArticles).length} | locales ${report.join(' ')}`,
)
