/**
 * Generates src/data/localized-coverage.generated.ts — the per-locale set of
 * article and glossary slugs that are ACTUALLY prerendered (drip/pilot-gated),
 * derived from the same route sets the prerender uses. langHref() consults it
 * to fall back to the EN URL for content that has no localized page yet,
 * instead of emitting a /<lang>/... link to a route that doesn't exist
 * (a soft 404 — HTTP 404 + SPA shell).
 */
import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import {
  LOCALIZED_ARTICLE_ROUTE_SET,
  LOCALIZED_GLOSSARY_ROUTE_SET,
  LOCALIZED_REVIEW_ROUTE_SET,
} from './prerender-routes'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LANGS = ['es', 'ru', 'uk', 'zh'] as const

// route '/es/articles/<slug>' -> { lang:'es', slug:'<slug>' }
function slugsByLang(routes: Set<string>, segment: string): Record<string, string[]> {
  const out: Record<string, string[]> = { es: [], ru: [], uk: [], zh: [] }
  for (const r of routes) {
    const parts = r.split('/').filter(Boolean) // [lang, segment, ...slug]
    if (parts.length < 3 || parts[1] !== segment) continue
    const lang = parts[0]
    if (lang in out) out[lang].push(parts.slice(2).join('/'))
  }
  for (const l of Object.keys(out)) out[l].sort()
  return out
}

const articles = slugsByLang(LOCALIZED_ARTICLE_ROUTE_SET, 'articles')
const glossary = slugsByLang(LOCALIZED_GLOSSARY_ROUTE_SET, 'glossary')

// Reviews have nested shapes: /<lang>/reviews/<slug>, /<lang>/reviews/vs/<slug>,
// /<lang>/reviews/compare/<slug>, /<lang>/reviews/<category-url-slug>, and the
// /<lang>/reviews index itself ('' remainder). Capture the full remainder after
// 'reviews' so langHref() can keep the locale prefix only for paths that exist.
function reviewRemaindersByLang(routes: Set<string>): Record<string, string[]> {
  const out: Record<string, string[]> = { es: [], ru: [], uk: [], zh: [] }
  for (const r of routes) {
    const parts = r.split('/').filter(Boolean) // [lang, 'reviews', ...rest]
    if (parts.length < 2 || parts[1] !== 'reviews') continue
    const lang = parts[0]
    if (lang in out) out[lang].push(parts.slice(2).join('/')) // '' for the index
  }
  for (const l of Object.keys(out)) out[l] = [...new Set(out[l])].sort()
  return out
}

const reviews = reviewRemaindersByLang(LOCALIZED_REVIEW_ROUTE_SET)

const body =
  `// AUTO-GENERATED by scripts/generate-localized-coverage.ts — do not edit.\n` +
  `// Per-locale slugs that have a prerendered localized page; used by langHref()\n` +
  `// to fall back to the EN URL for untranslated content (avoids /<lang>/... soft-404s).\n` +
  `export const LOCALIZED_COVERAGE: Record<string, { articles: Set<string>; glossary: Set<string>; reviews: Set<string> }> = {\n` +
  LANGS.map(
    (l) =>
      `  ${l}: {\n` +
      `    articles: new Set([${articles[l].map((s) => `'${s}'`).join(', ')}]),\n` +
      `    glossary: new Set([${glossary[l].map((s) => `'${s}'`).join(', ')}]),\n` +
      `    reviews: new Set([${reviews[l].map((s) => `'${s}'`).join(', ')}]),\n` +
      `  },`,
  ).join('\n') +
  `\n}\n`

writeFileSync(join(__dirname, '..', 'src', 'data', 'localized-coverage.generated.ts'), body)
console.log(
  `[localized-coverage] ${LANGS.map((l) => `${l}:${articles[l].length}a/${glossary[l].length}g/${reviews[l].length}r`).join(' ')}`,
)
