/**
 * IndexNow submission for ONDA Life.
 *
 * Reads dist/sitemap.xml (generated by sitemap.ts), diffs against the
 * previous run's state file, and POSTs only new/changed URLs to IndexNow.
 *
 * IndexNow is a single-endpoint protocol that fans out to Bing, Yandex,
 * Seznam, Naver and others. We submit to api.indexnow.org which forwards.
 *
 * Skip cases:
 *   - INDEXNOW_DISABLED=1 in env
 *   - dist/sitemap.xml missing
 *   - no URL changes since last run
 *
 * Run order: prerender.ts -> sitemap.ts -> indexnow.ts (tail of build).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = join(__dirname, '..', 'dist')
const sitemapPath = join(distDir, 'sitemap.xml')
const stateDir = join(__dirname, '..', '.cache')
const statePath = join(stateDir, 'indexnow-state.json')

const HOST = 'onda-life.com'
const KEY = '1918e61cfd9da62111b3ad204c79f12e'
const KEY_LOCATION = `https://${HOST}/${KEY}.txt`
const ENDPOINT = 'https://api.indexnow.org/indexnow'
const BATCH_SIZE = 10000 // IndexNow per-request URL limit

if (process.env.INDEXNOW_DISABLED === '1') {
  console.log('[indexnow] disabled via INDEXNOW_DISABLED=1, skipping')
  process.exit(0)
}

if (!existsSync(sitemapPath)) {
  console.log('[indexnow] dist/sitemap.xml not found, skipping')
  process.exit(0)
}

// Parse sitemap: extract <loc> + <lastmod> per <url> entry.
const xml = readFileSync(sitemapPath, 'utf-8')
const current = new Map<string, string>()
const urlBlockRe = /<url>([\s\S]*?)<\/url>/g
let m: RegExpExecArray | null
while ((m = urlBlockRe.exec(xml)) !== null) {
  const block = m[1]
  const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1]?.trim()
  const lastmod = block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1]?.trim() ?? ''
  if (loc) current.set(loc, lastmod)
}

if (current.size === 0) {
  console.log('[indexnow] sitemap has no <loc> entries, skipping')
  process.exit(0)
}

// Diff against previous state.
let previous: Record<string, string> = {}
if (existsSync(statePath)) {
  try {
    previous = JSON.parse(readFileSync(statePath, 'utf-8')) as Record<string, string>
  } catch {
    previous = {}
  }
}

const changed: string[] = []
for (const [loc, lastmod] of current) {
  if (previous[loc] !== lastmod) changed.push(loc)
}

if (changed.length === 0) {
  console.log('[indexnow] no URL changes since last submission, skipping')
  process.exit(0)
}

console.log(`[indexnow] submitting ${changed.length} URL(s) to ${ENDPOINT}`)

// Post in batches.
let okCount = 0
for (let i = 0; i < changed.length; i += BATCH_SIZE) {
  const batch = changed.slice(i, i + BATCH_SIZE)
  const body = JSON.stringify({
    host: HOST,
    key: KEY,
    keyLocation: KEY_LOCATION,
    urlList: batch,
  })
  try {
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body,
    })
    // 200 = accepted, 202 = accepted but processing, 422 = unprocessable
    // (e.g. unknown URLs), 429 = rate limit, 4xx = client error.
    if (res.status === 200 || res.status === 202) {
      okCount += batch.length
      console.log(`[indexnow] batch ${i / BATCH_SIZE + 1}: ${batch.length} URL(s) -> ${res.status}`)
    } else {
      const text = await res.text().catch(() => '')
      console.warn(`[indexnow] batch ${i / BATCH_SIZE + 1} failed: ${res.status} ${text.slice(0, 200)}`)
    }
  } catch (err) {
    console.warn(`[indexnow] batch ${i / BATCH_SIZE + 1} network error:`, (err as Error).message)
  }
}

// Update state file with the full current snapshot only if we got at least
// one accepted batch — otherwise next run will retry the whole diff.
if (okCount > 0) {
  if (!existsSync(stateDir)) mkdirSync(stateDir, { recursive: true })
  const snapshot: Record<string, string> = {}
  for (const [loc, lastmod] of current) snapshot[loc] = lastmod
  writeFileSync(statePath, JSON.stringify(snapshot, null, 2))
  console.log(`[indexnow] done: ${okCount}/${changed.length} URL(s) submitted, state saved`)
} else {
  console.warn('[indexnow] all batches failed, state not updated')
  process.exit(1)
}
