/**
 * Builds docs/science-pack/MISTRAL.md — ALL ONDA Science writing rules in ONE file, for Mistral to read.
 * It is assembled from the pack files (README + 01–09), so it can never disagree with them.
 * Run from landing/:
 *   npx tsx scripts/science-pack-bundle.ts          # regenerate (also regenerates 03-facts.md first)
 *   npx tsx scripts/science-pack-bundle.ts --check  # exit 1 if MISTRAL.md is stale
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import { execSync } from 'child_process'

const DIR = join(process.cwd(), 'docs', 'science-pack')
const OUT = join(DIR, 'MISTRAL.md')
const PARTS = [
  '01-quality-standard.md',
  '02-template.md',
  '03-facts.md',
  '04-sources.md',
  '05-banned-wording.md',
  '06-mvp-pages.md',
  '07-byline.md',
  '08-handoff-checklist.md',
  '09-acceptance-checklist.md',
]
const CHECK = process.argv.includes('--check')
if (!CHECK) execSync('npx tsx scripts/science-pack-facts.ts', { stdio: 'inherit' })

const read = (f: string) => readFileSync(join(DIR, f), 'utf8').replace(/\r\n/g, '\n').trim()
// Links between pack files become in-page anchors.
const anchor = (f: string) => `#${f.replace(/\.md$/, '')}`
const relink = (s: string) => PARTS.reduce((acc, f) => acc.split(`](${f})`).join(`](${anchor(f)})`), s)

const intro = `# ONDA Science — ALL rules for writing pages (single file for Mistral)

> **Generated** from \`landing/docs/science-pack/\` by \`npx tsx scripts/science-pack-bundle.ts\`. Do not edit this file — edit the pack files; this file is rebuilt from them.
> **Read the whole file before every writing session.** It is the binding standard. If anything here conflicts with older notes or specs, this file wins.

## How to work (short version)

1. You have **read-only** access to the repository for context. Do not push, commit or open pull requests.
2. Write **one page as one Markdown file**, starting from the template in section 2, for one of the 13 pages in section 6. English only.
3. Every number goes through \`{{fact:…}}\` (section 3) or a proposal \`{{proposed:P…}}\` (section 1, §1.11). Sources need a DOI or PMID; manufacturer/regulator documents use type \`official\` and only for device/regulatory facts.
4. Before handing in, go through the hand-off checklist (section 8). If you can run Node, run \`npx tsx scripts/check-science-content.ts --file <your-file.md>\` from \`landing/\` and attach the log; if you cannot, say so.
5. Send the file and the hand-off note to Yakiv. Claude Code checks it against section 9 and publishes it.

## Contents

${PARTS.map((f, i) => `${i + 1}. [${f}](${anchor(f)})`).join('\n')}
`

const body = PARTS.map((f) => {
  let s = read(f)
  if (f === '02-template.md') s = `# 2. Page template\n\nCopy everything inside the block below into a new file \`landing/content/science/<kind>/<slug>.md\`.\n\n\`\`\`\`markdown\n${s}\n\`\`\`\``
  return `<a id="${f.replace(/\.md$/, '')}"></a>\n\n${relink(s)}`
}).join('\n\n---\n\n')

const doc = `${intro}\n---\n\n${body}\n`

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : ''
  if (cur !== doc) { console.error('[science-pack] MISTRAL.md is stale — run npx tsx scripts/science-pack-bundle.ts'); process.exit(1) }
  console.log('[science-pack] MISTRAL.md up to date')
} else {
  writeFileSync(OUT, doc)
  console.log(`[science-pack] wrote MISTRAL.md (${PARTS.length} parts, ${Math.round(doc.length / 1024)} KB)`)
}
